-- ----------------------------------------------------------------
-- SCRIPT DE BASE DE DATOS 'BIBLIOTECA'
-- Generado por IA como ejercicio docente
-- Patrones: universidad + dulces + ajedrez
-- ----------------------------------------------------------------

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD';

-- 1. ELIMINACIÓN DE TABLAS (orden inverso a creación)

BEGIN
  FOR c IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'DETALLE_PRESTAMO', 'PRESTAMO', 'EJEMPLAR', 'LIBRO_AUTOR',
    'AUTOR', 'LIBRO', 'EDITORIAL', 'CATEGORIA',
    'SOCIO', 'EMPLEADO', 'MIEMBRO'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

-- 2. CREACIÓN DE TABLAS

CREATE TABLE miembro (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni          VARCHAR2(9) UNIQUE NOT NULL,
    nombre       VARCHAR2(25) NOT NULL,
    apellidos    VARCHAR2(50) NOT NULL,
    telefono     VARCHAR2(9),
    email        VARCHAR2(60),
    fecha_alta   DATE NOT NULL,
    tipo         VARCHAR2(8) NOT NULL CHECK (tipo IN ('socio', 'empleado'))
);

CREATE TABLE empleado (
    id_miembro   NUMBER PRIMARY KEY,
    cargo        VARCHAR2(30) NOT NULL,
    salario      NUMBER(8, 2),
    FOREIGN KEY (id_miembro) REFERENCES miembro(id)
);

CREATE TABLE socio (
    id_miembro         NUMBER PRIMARY KEY,
    fecha_nacimiento   DATE NOT NULL,
    direccion          VARCHAR2(50) NOT NULL,
    activo             NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1)),
    FOREIGN KEY (id_miembro) REFERENCES miembro(id)
);

CREATE TABLE categoria (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR2(40) NOT NULL UNIQUE,
    descripcion        VARCHAR2(100),
    id_categoria_padre NUMBER,
    FOREIGN KEY (id_categoria_padre) REFERENCES categoria(id)
);

CREATE TABLE editorial (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(60) NOT NULL UNIQUE,
    pais     VARCHAR2(30)
);

CREATE TABLE autor (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(25) NOT NULL,
    apellidos       VARCHAR2(50) NOT NULL,
    nacionalidad    VARCHAR2(30)
);

CREATE TABLE libro (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn           VARCHAR2(13) UNIQUE NOT NULL,
    titulo         VARCHAR2(100) NOT NULL,
    anyo           NUMBER(4),
    paginas        NUMBER(4),
    id_categoria   NUMBER NOT NULL,
    id_editorial   NUMBER NOT NULL,
    FOREIGN KEY (id_categoria) REFERENCES categoria(id),
    FOREIGN KEY (id_editorial) REFERENCES editorial(id)
);

CREATE TABLE libro_autor (
    id_libro   NUMBER NOT NULL,
    id_autor   NUMBER NOT NULL,
    PRIMARY KEY (id_libro, id_autor),
    FOREIGN KEY (id_libro) REFERENCES libro(id),
    FOREIGN KEY (id_autor) REFERENCES autor(id)
);

CREATE TABLE ejemplar (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_libro         NUMBER NOT NULL,
    codigo_barras    VARCHAR2(20) UNIQUE NOT NULL,
    estado           VARCHAR2(12) NOT NULL CHECK (estado IN ('disponible', 'prestado', 'baja')),
    FOREIGN KEY (id_libro) REFERENCES libro(id)
);

CREATE TABLE prestamo (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio       NUMBER NOT NULL,
    fecha          DATE NOT NULL,
    fecha_limite   DATE NOT NULL,
    FOREIGN KEY (id_socio) REFERENCES socio(id_miembro)
);

CREATE TABLE detalle_prestamo (
    id_prestamo       NUMBER NOT NULL,
    id_ejemplar       NUMBER NOT NULL,
    fecha_devolucion  DATE,
    PRIMARY KEY (id_prestamo, id_ejemplar),
    FOREIGN KEY (id_prestamo) REFERENCES prestamo(id),
    FOREIGN KEY (id_ejemplar) REFERENCES ejemplar(id)
);

-- 3. INSERCIÓN DE DATOS DE EJEMPLO

-- MIEMBROS (empleados)
INSERT INTO miembro VALUES (1, '11111111A', 'Marta', 'García López', '912345678', 'marta@biblioteca.es', '2020/01/15', 'empleado');
INSERT INTO miembro VALUES (2, '22222222B', 'Luis', 'Martínez Ruiz', '912345679', 'luis@biblioteca.es', '2021/03/01', 'empleado');

-- MIEMBROS (socios)
INSERT INTO miembro VALUES (3, '33333333C', 'Ana', 'Pérez Sánchez', '612345678', 'ana@mail.com', '2022/06/10', 'socio');
INSERT INTO miembro VALUES (4, '44444444D', 'Carlos', 'Jiménez Mora', '612345679', 'carlos@mail.com', '2022/09/20', 'socio');
INSERT INTO miembro VALUES (5, '55555555E', 'Lucía', 'Hernández Gil', '612345680', NULL, '2023/02/14', 'socio');
INSERT INTO miembro VALUES (6, '66666666F', 'David', 'Torres Vega', '612345681', 'david@mail.com', '2023/05/30', 'socio');

-- EMPLEADOS
INSERT INTO empleado VALUES (1, 'Bibliotecario', 24000);
INSERT INTO empleado VALUES (2, 'Auxiliar', 18000);

-- SOCIOS
INSERT INTO socio VALUES (3, '1992/04/18', 'C/ Mayor 10, Madrid', 1);
INSERT INTO socio VALUES (4, '1988/11/25', 'Avda. Constitución 5, Madrid', 1);
INSERT INTO socio VALUES (5, '2000/07/03', 'C/ Sol 22, Madrid', 1);
INSERT INTO socio VALUES (6, '1995/09/12', 'Plaza España 3, Madrid', 0);

-- CATEGORÍAS (con auto-referencia)
INSERT INTO categoria VALUES (1, 'Ficción', 'Literatura de ficción en todas sus formas', NULL);
INSERT INTO categoria VALUES (2, 'No ficción', 'Obras basadas en hechos reales', NULL);
INSERT INTO categoria VALUES (3, 'Novela', 'Novela contemporánea y clásica', 1);
INSERT INTO categoria VALUES (4, 'Poesía', 'Poesía de todas las épocas', 1);
INSERT INTO categoria VALUES (5, 'Ciencia', 'Divulgación y ensayo científico', 2);
INSERT INTO categoria VALUES (6, 'Historia', 'Libros de historia universal', 2);

-- EDITORIALES
INSERT INTO editorial VALUES (1, 'Alfaguara', 'España');
INSERT INTO editorial VALUES (2, 'Anagrama', 'España');
INSERT INTO editorial VALUES (3, 'Debate', 'España');
INSERT INTO editorial VALUES (4, 'Tusquets', 'España');

-- AUTORES
INSERT INTO autor VALUES (1, 'Gabriel', 'García Márquez', 'Colombia');
INSERT INTO autor VALUES (2, 'Mario', 'Vargas Llosa', 'Perú');
INSERT INTO autor VALUES (3, 'Isabel', 'Allende', 'Chile');
INSERT INTO autor VALUES (4, 'Jorge Luis', 'Borges', 'Argentina');
INSERT INTO autor VALUES (5, 'Yuval Noah', 'Harari', 'Israel');

-- LIBROS
INSERT INTO libro VALUES (1, '9788420471839', 'Cien años de soledad', 1967, 432, 3, 1);
INSERT INTO libro VALUES (2, '9788420471846', 'El amor en los tiempos del cólera', 1985, 368, 3, 1);
INSERT INTO libro VALUES (3, '9788432232184', 'La ciudad y los perros', 1963, 416, 3, 2);
INSERT INTO libro VALUES (4, '9788401337204', 'La casa de los espíritus', 1982, 496, 3, 4);
INSERT INTO libro VALUES (5, '9788420633684', 'Ficciones', 1944, 224, 4, 1);
INSERT INTO libro VALUES (6, '9788499928683', 'Sapiens', 2011, 496, 5, 3);
INSERT INTO libro VALUES (7, '9788499928676', 'Homo Deus', 2015, 528, 5, 3);

-- LIBRO_AUTOR (N:M)
INSERT INTO libro_autor VALUES (1, 1);
INSERT INTO libro_autor VALUES (2, 1);
INSERT INTO libro_autor VALUES (3, 2);
INSERT INTO libro_autor VALUES (4, 3);
INSERT INTO libro_autor VALUES (5, 4);
INSERT INTO libro_autor VALUES (6, 5);
INSERT INTO libro_autor VALUES (7, 5);

-- EJEMPLARES
INSERT INTO ejemplar VALUES (1, 1, 'BIB-001-A', 'prestado');
INSERT INTO ejemplar VALUES (2, 1, 'BIB-001-B', 'disponible');
INSERT INTO ejemplar VALUES (3, 2, 'BIB-002-A', 'disponible');
INSERT INTO ejemplar VALUES (4, 3, 'BIB-003-A', 'prestado');
INSERT INTO ejemplar VALUES (5, 4, 'BIB-004-A', 'disponible');
INSERT INTO ejemplar VALUES (6, 5, 'BIB-005-A', 'baja');
INSERT INTO ejemplar VALUES (7, 6, 'BIB-006-A', 'disponible');
INSERT INTO ejemplar VALUES (8, 6, 'BIB-006-B', 'prestado');
INSERT INTO ejemplar VALUES (9, 7, 'BIB-007-A', 'disponible');

-- PRÉSTAMOS
INSERT INTO prestamo VALUES (1, 3, '2025/04/01', '2025/04/15');
INSERT INTO prestamo VALUES (2, 4, '2025/04/05', '2025/04/19');
INSERT INTO prestamo VALUES (3, 3, '2025/04/10', '2025/04/24');

-- DETALLE_PRÉSTAMO
INSERT INTO detalle_prestamo VALUES (1, 1, NULL);
INSERT INTO detalle_prestamo VALUES (2, 4, '2025/04/18');
INSERT INTO detalle_prestamo VALUES (3, 8, NULL);

-- 4. DATOS ADICIONALES PARA EJERCICIOS

-- MIEMBROS (más empleados)
INSERT INTO miembro VALUES (7, '77777777G', 'Elena', 'Navarro Díaz', '912345682', 'elena@biblioteca.es', '2022/11/01', 'empleado');
INSERT INTO miembro VALUES (8, '88888888H', 'Pedro', 'Ramírez Sanz', NULL, 'pedro@biblioteca.es', '2023/01/10', 'empleado');

-- MIEMBROS (más socios)
INSERT INTO miembro VALUES (9,  '99999999J', 'Sofía', 'Morales Ruiz', NULL, 'sofia@mail.com', '2023/03/05', 'socio');
INSERT INTO miembro VALUES (10, '10101010K', 'Javier', 'Ortega Lerma', '612345682', 'javier@mail.com', '2023/06/15', 'socio');
INSERT INTO miembro VALUES (11, '11111110L', 'Laura', 'Díaz Romero', '612345683', 'laura@mail.com', '2024/01/20', 'socio');
INSERT INTO miembro VALUES (12, '12121212M', 'Miguel', 'Álvarez Vera', NULL, 'miguel@mail.com', '2024/02/28', 'socio');
INSERT INTO miembro VALUES (13, '13131313N', 'Carmen', 'Ruiz Pastor', '612345684', 'carmen@mail.com', '2024/04/10', 'socio');
INSERT INTO miembro VALUES (14, '14141414P', 'Alberto', 'Molina Gil', '612345685', 'alberto@mail.com', '2024/05/15', 'socio');

-- EMPLEADOS (más)
INSERT INTO empleado VALUES (7, 'Director', 32000);
INSERT INTO empleado VALUES (8, 'Auxiliar', 16000);

-- SOCIOS (más)
INSERT INTO socio VALUES (9,  '2001/09/15', 'C/ Luna 8, Madrid', 1);
INSERT INTO socio VALUES (10, '1990/12/01', 'Avda. América 14, Madrid', 1);
INSERT INTO socio VALUES (11, '1998/07/22', 'C/ Sierra 3, Madrid', 1);
INSERT INTO socio VALUES (12, '1985/03/18', 'C/ Pino 45, Madrid', 1);
INSERT INTO socio VALUES (13, '2002/11/30', 'C/ Roble 12, Madrid', 1);
INSERT INTO socio VALUES (14, '1978/06/05', 'C/ Olmo 7, Madrid', 1);

-- CATEGORÍAS (más, alguna sin libros)
INSERT INTO categoria VALUES (7, 'Infantil', 'Libros para niños y jóvenes', 1);
INSERT INTO categoria VALUES (8, 'Filosofía', 'Obras de pensamiento filosófico', 2);

-- EDITORIALES (más, alguna sin libros)
INSERT INTO editorial VALUES (5, 'Planeta', 'España');
INSERT INTO editorial VALUES (6, 'Siglo XXI', 'México');
INSERT INTO editorial VALUES (7, 'Cátedra', 'España');

-- AUTORES (más)
INSERT INTO autor VALUES (6, 'Julio', 'Cortázar', 'Argentina');
INSERT INTO autor VALUES (7, 'Pablo', 'Neruda', 'Chile');
INSERT INTO autor VALUES (8, 'Miguel', 'Cervantes', 'España');
INSERT INTO autor VALUES (9, 'Federico', 'García Lorca', 'España');
INSERT INTO autor VALUES (10, 'Stephen', 'Hawking', 'Reino Unido');
INSERT INTO autor VALUES (11, 'Antonio', 'Machado', 'España');

-- LIBROS (más)
INSERT INTO libro VALUES (8,  '9788437604947', 'Rayuela', 1963, 576, 3, 5);
INSERT INTO libro VALUES (9,  '9788420633691', 'El Aleph', 1949, 208, 4, 1);
INSERT INTO libro VALUES (10, '9788401016734', 'Veinte poemas de amor', 1924, 120, 4, 4);
INSERT INTO libro VALUES (11, '9788420471853', 'Crónica de una muerte anunciada', 1981, 160, 3, 1);
INSERT INTO libro VALUES (12, '9788437604948', 'Bestiario', 1951, 192, 3, 6);
INSERT INTO libro VALUES (13, '9788499928690', '21 lecciones para el siglo XXI', 2018, 400, 5, 3);
INSERT INTO libro VALUES (14, '9788423350183', 'La sombra del viento', 2001, 576, 3, 5);
INSERT INTO libro VALUES (15, '9788432217310', 'El Quijote', 1605, 920, 3, 7);
INSERT INTO libro VALUES (16, '9788420633721', 'El hacedor', 1960, 128, 4, 1);
INSERT INTO libro VALUES (17, '9788498386747', 'El principito', 1943, 96, 7, 5);
INSERT INTO libro VALUES (18, '9788499928706', 'Breve historia del tiempo', 1988, 256, 5, 3);
INSERT INTO libro VALUES (19, '9788467021970', 'Romancero gitano', 1928, 144, 4, 5);
INSERT INTO libro VALUES (20, '9788420471860', 'Del Amor y otros demonios', 1994, 224, 3, 1);
INSERT INTO libro VALUES (21, '9788432232191', 'Pantaleón y las visitadoras', 1973, 352, 3, 2);
INSERT INTO libro VALUES (22, '9788401337211', 'Paula', 1994, 368, 2, 4);

-- LIBRO_AUTOR (más, varios con múltiples autores)
INSERT INTO libro_autor VALUES (8, 6);
INSERT INTO libro_autor VALUES (9, 4);
INSERT INTO libro_autor VALUES (10, 7);
INSERT INTO libro_autor VALUES (11, 1);
INSERT INTO libro_autor VALUES (12, 6);
INSERT INTO libro_autor VALUES (13, 5);
INSERT INTO libro_autor VALUES (14, 3);
INSERT INTO libro_autor VALUES (15, 8);
INSERT INTO libro_autor VALUES (16, 4);
INSERT INTO libro_autor VALUES (17, 9);
INSERT INTO libro_autor VALUES (18, 10);
INSERT INTO libro_autor VALUES (19, 9);
INSERT INTO libro_autor VALUES (20, 1);
INSERT INTO libro_autor VALUES (21, 2);
INSERT INTO libro_autor VALUES (22, 3);

-- EJEMPLARES (más)
INSERT INTO ejemplar VALUES (10, 8,  'BIB-008-A', 'disponible');
INSERT INTO ejemplar VALUES (11, 8,  'BIB-008-B', 'disponible');
INSERT INTO ejemplar VALUES (12, 9,  'BIB-009-A', 'disponible');
INSERT INTO ejemplar VALUES (13, 10, 'BIB-010-A', 'disponible');
INSERT INTO ejemplar VALUES (14, 10, 'BIB-010-B', 'disponible');
INSERT INTO ejemplar VALUES (15, 11, 'BIB-011-A', 'disponible');
INSERT INTO ejemplar VALUES (16, 12, 'BIB-012-A', 'baja');
INSERT INTO ejemplar VALUES (17, 13, 'BIB-013-A', 'disponible');
INSERT INTO ejemplar VALUES (18, 13, 'BIB-013-B', 'prestado');
INSERT INTO ejemplar VALUES (19, 14, 'BIB-014-A', 'prestado');
INSERT INTO ejemplar VALUES (20, 14, 'BIB-014-B', 'prestado');
INSERT INTO ejemplar VALUES (21, 15, 'BIB-015-A', 'disponible');
INSERT INTO ejemplar VALUES (22, 15, 'BIB-015-B', 'disponible');
INSERT INTO ejemplar VALUES (23, 15, 'BIB-015-C', 'disponible');
INSERT INTO ejemplar VALUES (24, 16, 'BIB-016-A', 'disponible');
INSERT INTO ejemplar VALUES (25, 17, 'BIB-017-A', 'disponible');
INSERT INTO ejemplar VALUES (26, 18, 'BIB-018-A', 'disponible');
INSERT INTO ejemplar VALUES (27, 19, 'BIB-019-A', 'baja');
INSERT INTO ejemplar VALUES (28, 20, 'BIB-020-A', 'disponible');
INSERT INTO ejemplar VALUES (29, 20, 'BIB-020-B', 'disponible');
INSERT INTO ejemplar VALUES (30, 21, 'BIB-021-A', 'disponible');
INSERT INTO ejemplar VALUES (31, 22, 'BIB-022-A', 'disponible');

-- PRÉSTAMOS (más)
INSERT INTO prestamo VALUES (4, 5,  '2025/01/15', '2025/01/29');
INSERT INTO prestamo VALUES (5, 5,  '2025/02/01', '2025/02/15');
INSERT INTO prestamo VALUES (6, 9,  '2025/03/10', '2025/03/24');
INSERT INTO prestamo VALUES (7, 10, '2025/03/20', '2025/04/03');
INSERT INTO prestamo VALUES (8, 10, '2025/04/12', '2025/04/26');
INSERT INTO prestamo VALUES (9, 11, '2025/04/15', '2025/04/29');

-- DETALLE_PRÉSTAMO (más)
INSERT INTO detalle_prestamo VALUES (4, 6,  '2025/01/25');
INSERT INTO detalle_prestamo VALUES (4, 13, '2025/01/28');
INSERT INTO detalle_prestamo VALUES (5, 13, '2025/02/10');
INSERT INTO detalle_prestamo VALUES (5, 5,  '2025/02/12');
INSERT INTO detalle_prestamo VALUES (6, 14, '2025/03/22');
INSERT INTO detalle_prestamo VALUES (7, 18, NULL);
INSERT INTO detalle_prestamo VALUES (8, 19, NULL);
INSERT INTO detalle_prestamo VALUES (8, 20, NULL);
INSERT INTO detalle_prestamo VALUES (9, 26, NULL);

-- 5. MÁS DATOS PARA GARANTIZAR QUE TODOS LOS EJERCICIOS TIENEN RESPUESTA

-- MIEMBROS (más socios)
INSERT INTO miembro VALUES (15, '15151515Q', 'Raquel', 'Serrano Blanco', '612345686', 'raquel@mail.com', '2024/06/01', 'socio');
INSERT INTO miembro VALUES (16, '16161616R', 'Daniel', 'Castro Gómez', NULL, 'daniel@mail.com', '2024/07/10', 'socio');
INSERT INTO miembro VALUES (17, '17171717S', 'Patricia', 'Vega Molina', '612345687', 'patricia@mail.com', '2024/09/05', 'socio');
INSERT INTO miembro VALUES (18, '18181818T', 'Hugo', 'Delgado Sanz', '612345688', 'hugo@mail.com', '2024/10/20', 'socio');
INSERT INTO miembro VALUES (19, '19191919U', 'Eva', 'Cruz Ramos', '612345689', 'eva@mail.com', '2025/01/08', 'socio');

-- SOCIOS (más)
INSERT INTO socio VALUES (15, '1993/08/14', 'C/ Álamo 5, Madrid', 1);
INSERT INTO socio VALUES (16, '1997/11/25', 'C/ Sauce 9, Madrid', 1);
INSERT INTO socio VALUES (17, '1982/04/30', 'Avda. de la Paz 22, Madrid', 1);
INSERT INTO socio VALUES (18, '1999/01/12', 'C/ Nogal 15, Madrid', 1);
INSERT INTO socio VALUES (19, '2003/05/20', 'C/ Ciprés 3, Madrid', 1);

-- EMPLEADOS (más)
INSERT INTO miembro VALUES (20, '20202020V', 'Sara', 'Lorenzo Hurtado', '912345690', 'sara@biblioteca.es', '2019/05/01', 'empleado');
INSERT INTO miembro VALUES (21, '21212121W', 'Raúl', 'Cano Navarro', '912345691', 'raul@biblioteca.es', '2018/09/15', 'empleado');
INSERT INTO miembro VALUES (22, '22222222X', 'Nuria', 'Pastor Gil', '912345692', 'nuria@biblioteca.es', '2023/08/01', 'empleado');
INSERT INTO empleado VALUES (20, 'Bibliotecario Jefe', 28000);
INSERT INTO empleado VALUES (21, 'Técnico Archivo', 22000);
INSERT INTO empleado VALUES (22, 'Auxiliar', 17000);

-- CATEGORÍAS (más)
INSERT INTO categoria VALUES (9, 'Tecnología', 'Informática y nuevas tecnologías', 2);
INSERT INTO categoria VALUES (10, 'Arte', 'Pintura, música y cine', 2);

-- EDITORIALES (más, alguna sin libros ya existe - Cátedra)
INSERT INTO editorial VALUES (8, 'Editorial Pre-Texto', 'España');
INSERT INTO editorial VALUES (9, 'Alianza', 'España');

-- AUTORES (más)
INSERT INTO autor VALUES (12, 'Laura', 'Esquivel', 'México');
INSERT INTO autor VALUES (13, 'Juan', 'Rulfo', 'México');
INSERT INTO autor VALUES (14, 'Alejandro', 'Dumas', 'Francia');
INSERT INTO autor VALUES (15, 'Jane', 'Austen', 'Reino Unido');
INSERT INTO autor VALUES (16, 'George', 'Orwell', 'Reino Unido');
INSERT INTO autor VALUES (17, 'Gabriel', 'Roldán', 'Colombia');
INSERT INTO autor VALUES (18, 'Ángeles', 'Mastretta', 'México');
INSERT INTO autor VALUES (19, 'Rosa', 'Montero', 'España');

-- LIBROS (más)
INSERT INTO libro VALUES (23, '9788420471877', 'El otoño del patriarca', 1975, 320, 3, 1);
INSERT INTO libro VALUES (24, '9788498386754', 'Como agua para chocolate', 1989, 256, 3, 5);
INSERT INTO libro VALUES (25, '9788437604954', 'Pedro Páramo', 1955, 160, 3, 6);
INSERT INTO libro VALUES (26, '9788420674182', '1984', 1949, 352, 3, 9);
INSERT INTO libro VALUES (27, '9788420674199', 'Rebelión en la granja', 1945, 144, 3, 9);
INSERT INTO libro VALUES (28, '9788498386761', 'Orgullo y prejuicio', 1813, 480, 3, 8);
INSERT INTO libro VALUES (29, '9788423350190', 'El conde de Montecristo', 1844, 1200, 3, 9);
INSERT INTO libro VALUES (30, '9788467021987', 'La colmena', 1951, 352, 3, 5);
INSERT INTO libro VALUES (31, '9788499898641', 'El mundo de Sofía', 1991, 656, 8, 5);
INSERT INTO libro VALUES (32, '9788420633738', 'Los reyes', 1949, 80, 4, 1);
INSERT INTO libro VALUES (33, '9788401016741', 'Antología poética', 1970, 256, 4, 7);
INSERT INTO libro VALUES (34, '9788499928713', 'El universo en una cáscara de nuez', 2001, 240, 5, 3);
INSERT INTO libro VALUES (35, '9788499928720', 'La teoría del todo', 2002, 192, 5, 3);
INSERT INTO libro VALUES (36, '9788423350206', 'Los pilares de la Tierra', 1989, 1040, 6, 5);
INSERT INTO libro VALUES (37, '9788498386778', 'La catedral del mar', 2006, 640, 6, 5);
INSERT INTO libro VALUES (38, '9788467021994', 'El tiempo entre costuras', 2009, 640, 6, 5);

-- LIBRO_AUTOR (más)
INSERT INTO libro_autor VALUES (23, 1);
INSERT INTO libro_autor VALUES (24, 12);
INSERT INTO libro_autor VALUES (25, 13);
INSERT INTO libro_autor VALUES (26, 16);
INSERT INTO libro_autor VALUES (27, 16);
INSERT INTO libro_autor VALUES (28, 15);
INSERT INTO libro_autor VALUES (29, 14);
INSERT INTO libro_autor VALUES (30, 11);
INSERT INTO libro_autor VALUES (31, 12);
INSERT INTO libro_autor VALUES (32, 4);
INSERT INTO libro_autor VALUES (33, 11);
INSERT INTO libro_autor VALUES (34, 10);
INSERT INTO libro_autor VALUES (35, 10);
INSERT INTO libro_autor VALUES (36, 14);
INSERT INTO libro_autor VALUES (37, 17);
INSERT INTO libro_autor VALUES (38, 19);

-- EJEMPLARES (más)
INSERT INTO ejemplar VALUES (32, 23, 'BIB-023-A', 'disponible');
INSERT INTO ejemplar VALUES (33, 23, 'BIB-023-B', 'disponible');
INSERT INTO ejemplar VALUES (34, 24, 'BIB-024-A', 'disponible');
INSERT INTO ejemplar VALUES (35, 24, 'BIB-024-B', 'prestado');
INSERT INTO ejemplar VALUES (36, 24, 'BIB-024-C', 'disponible');
INSERT INTO ejemplar VALUES (37, 25, 'BIB-025-A', 'disponible');
INSERT INTO ejemplar VALUES (38, 26, 'BIB-026-A', 'prestado');
INSERT INTO ejemplar VALUES (39, 26, 'BIB-026-B', 'prestado');
INSERT INTO ejemplar VALUES (40, 26, 'BIB-026-C', 'disponible');
INSERT INTO ejemplar VALUES (41, 27, 'BIB-027-A', 'disponible');
INSERT INTO ejemplar VALUES (42, 28, 'BIB-028-A', 'disponible');
INSERT INTO ejemplar VALUES (43, 28, 'BIB-028-B', 'disponible');
INSERT INTO ejemplar VALUES (44, 29, 'BIB-029-A', 'disponible');
INSERT INTO ejemplar VALUES (45, 30, 'BIB-030-A', 'disponible');
INSERT INTO ejemplar VALUES (46, 30, 'BIB-030-B', 'disponible');
INSERT INTO ejemplar VALUES (47, 31, 'BIB-031-A', 'disponible');
INSERT INTO ejemplar VALUES (48, 31, 'BIB-031-B', 'disponible');
INSERT INTO ejemplar VALUES (49, 32, 'BIB-032-A', 'disponible');
INSERT INTO ejemplar VALUES (50, 33, 'BIB-033-A', 'disponible');
INSERT INTO ejemplar VALUES (51, 34, 'BIB-034-A', 'disponible');
INSERT INTO ejemplar VALUES (52, 35, 'BIB-035-A', 'disponible');
INSERT INTO ejemplar VALUES (53, 36, 'BIB-036-A', 'disponible');
INSERT INTO ejemplar VALUES (54, 36, 'BIB-036-B', 'disponible');
INSERT INTO ejemplar VALUES (55, 37, 'BIB-037-A', 'disponible');
INSERT INTO ejemplar VALUES (56, 38, 'BIB-038-A', 'prestado');
INSERT INTO ejemplar VALUES (57, 38, 'BIB-038-B', 'disponible');

-- PRÉSTAMOS (más)
INSERT INTO prestamo VALUES (10, 13, '2025/02/05', '2025/02/19');
INSERT INTO prestamo VALUES (11, 13, '2025/03/01', '2025/03/15');
INSERT INTO prestamo VALUES (12, 11, '2025/03/05', '2025/03/19');
INSERT INTO prestamo VALUES (13, 13, '2025/04/20', '2025/05/04');
INSERT INTO prestamo VALUES (14, 14, '2025/05/02', '2025/05/16');
INSERT INTO prestamo VALUES (15, 15, '2025/05/05', '2025/05/19');

-- DETALLE_PRÉSTAMO (más)
INSERT INTO detalle_prestamo VALUES (10, 35, '2025/02/18');
INSERT INTO detalle_prestamo VALUES (10, 24, '2025/02/19');
INSERT INTO detalle_prestamo VALUES (11, 31, '2025/03/14');
INSERT INTO detalle_prestamo VALUES (12, 38, '2025/03/18');
INSERT INTO detalle_prestamo VALUES (12, 39, '2025/03/18');
INSERT INTO detalle_prestamo VALUES (13, 56, NULL);
INSERT INTO detalle_prestamo VALUES (14, 34, NULL);
INSERT INTO detalle_prestamo VALUES (14, 43, NULL);
INSERT INTO detalle_prestamo VALUES (15, 11, NULL);
INSERT INTO detalle_prestamo VALUES (15, 47, NULL);

-- LIBROS SIN EJEMPLARES (para ejercicio: libros nunca prestados y LEFT JOIN)
INSERT INTO libro VALUES (39, '9788423350213', 'Libro perdido sin ejemplares', 2015, 300, 3, 1);
INSERT INTO libro_autor VALUES (39, 11);

-- EJEMPLARES DE BAJA (3 más para dar variedad)
INSERT INTO ejemplar VALUES (58, 30, 'BIB-030-C', 'baja');

-- PRÉSTAMO VENCIDO LARGO (para consultas de filtro temporal)
INSERT INTO prestamo VALUES (16, 19, '2024/12/01', '2024/12/15');
INSERT INTO detalle_prestamo VALUES (16, 5, NULL);

COMMIT;
