-- ============================================================
--  BASE DE DATOS 2: CATÁLOGO DE PELÍCULAS 
--  Ejecutar sobre el esquema peliculas (usuario PELICULAS)
-- ============================================================
commit;
-- Limpieza previa (orden inverso a FK)
DROP TABLE peliculas.generos_aptos_tp CASCADE CONSTRAINTS PURGE;
DROP TABLE peliculas.reparto          CASCADE CONSTRAINTS PURGE;
DROP TABLE peliculas.pelicula         CASCADE CONSTRAINTS PURGE;
DROP TABLE peliculas.actores          CASCADE CONSTRAINTS PURGE;
DROP TABLE peliculas.generos          CASCADE CONSTRAINTS PURGE;

-- ============================================================
--  CREACIÓN DE TABLAS 
-- ============================================================

CREATE TABLE peliculas.generos (
    idgenero      NUMBER(4)     GENERATED BY DEFAULT AS IDENTITY
                                CONSTRAINT pk_generos     PRIMARY KEY,
    nombre        VARCHAR2(50)  CONSTRAINT nn_gen_nombre  NOT NULL,
    descripcion   VARCHAR2(500),
    clasificacion VARCHAR2(10),
    CONSTRAINT uq_gen_nombre UNIQUE (nombre)
);

CREATE TABLE peliculas.actores (
    idactor              NUMBER(6)     CONSTRAINT pk_actores    PRIMARY KEY,
    nombre               VARCHAR2(50)  CONSTRAINT nn_act_nombre NOT NULL,
    apellidos            VARCHAR2(100) CONSTRAINT nn_act_ape    NOT NULL,
    salario_mes_rodaje   NUMBER(12,2)  CONSTRAINT nn_act_sal    NOT NULL,
    pais_nacimiento      VARCHAR2(50)  CONSTRAINT nn_act_pais   NOT NULL,
    observaciones        VARCHAR2(200),
    CONSTRAINT chk_act_salario CHECK (salario_mes_rodaje > 0)
);

CREATE TABLE peliculas.pelicula (
    idpelicula       NUMBER(6)     CONSTRAINT pk_pelicula   PRIMARY KEY,
    nombre           VARCHAR2(150) CONSTRAINT nn_pel_nombre NOT NULL,
    idgenero         NUMBER(4)     CONSTRAINT nn_pel_genero NOT NULL,
    fecha_estreno    DATE          CONSTRAINT nn_pel_fecha  NOT NULL,
    pais             VARCHAR2(50)  CONSTRAINT nn_pel_pais   NOT NULL,
    duracion         NUMBER(4),
    recaudacion      NUMBER(14,2),
    CONSTRAINT fk_pel_genero    FOREIGN KEY (idgenero) REFERENCES peliculas.generos  (idgenero),
    CONSTRAINT chk_pel_duracion CHECK (duracion         >  0),
    CONSTRAINT chk_pel_recaud   CHECK (recaudacion      >= 0)
);

CREATE TABLE peliculas.reparto (
    idpelicula NUMBER(6)    CONSTRAINT nn_rep_pel   NOT NULL,
    idactor    NUMBER(6)    CONSTRAINT nn_rep_act   NOT NULL,
    papel      VARCHAR2(20) CONSTRAINT nn_rep_papel NOT NULL,
    meses_rodaje NUMBER      DEFAULT 1,
    CONSTRAINT pk_reparto      PRIMARY KEY (idpelicula, idactor),
    CONSTRAINT fk_rep_pelicula FOREIGN KEY (idpelicula) REFERENCES peliculas.pelicula (idpelicula),
    CONSTRAINT fk_rep_actor    FOREIGN KEY (idactor)    REFERENCES peliculas.actores  (idactor),
    CONSTRAINT chk_rep_papel   CHECK (papel IN ('principal','secundario','cameo')),
    CONSTRAINT chk_rep_meses   CHECK (meses_rodaje >= 0)
);

CREATE TABLE peliculas.generos_aptos_tp (
    idgenero      NUMBER(4)     GENERATED BY DEFAULT AS IDENTITY
                                CONSTRAINT pk_nuevos_gen   PRIMARY KEY,
    nombre        VARCHAR2(50)  CONSTRAINT nn_ngen_nombre  NOT NULL,
    descripcion   VARCHAR2(500),
    clasificacion VARCHAR2(10),
    CONSTRAINT uq_ngen_nombre UNIQUE (nombre)
);

-- ============================================================
--  INSERTS: GÉNEROS
-- ============================================================

INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Acción',         'Películas con persecuciones, peleas y secuencias de alto impacto visual',      '+12');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Comedia',        'Películas diseñadas para provocar la risa a través de situaciones cómicas',     'TP');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Drama',          'Películas centradas en el desarrollo emocional y los conflictos humanos',        'TP');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Ciencia ficción','Películas ambientadas en futuros imaginarios con tecnología avanzada',            '+12');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Terror',         'Películas diseñadas para provocar miedo y tensión en el espectador',             '+16');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Animación',      'Películas creadas mediante técnicas de animación digital o tradicional',          'TP');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Thriller',       'Películas de intriga y suspense con tramas complejas y giros inesperados',        '+12');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Romance',        'Películas centradas en relaciones amorosas y su desarrollo sentimental',          'TP');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Aventura',       'Películas con personajes en viajes o misiones llenas de acción y descubrimiento', 'TP');
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Documental',     NULL, NULL);
INSERT INTO peliculas.generos (nombre, descripcion, clasificacion) VALUES ('Fantasía',       NULL, NULL);

-- ============================================================
--  INSERTS: ACTORES 
-- ============================================================

INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (1,  'James',     'McAllister',        1500000.00, 'Estados Unidos', NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (2,  'Scarlett',  'Reynolds',          1800000.00, 'Estados Unidos', NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (3,  'Antonio',   'Vega Morales',       500000.00, 'España',         NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (4,  'Penélope',  'Ruiz Solana',        800000.00, 'España',         NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (5,  'Luca',      'Bianchi',            600000.00, 'Italia',         NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (6,  'Marie',     'Leclerc',            750000.00, 'Francia',        NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (7,  'Hiroshi',   'Tanaka',             450000.00, 'Japón',          NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (8,  'Valentina', 'Cruz Medina',        350000.00, 'México',         NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (9,  'Samuel',    'Okafor',             550000.00, 'Nigeria',        NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (10, 'Emma',      'Whitfield',         1200000.00, 'Reino Unido',    NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (11, 'Robert',    'Donner',            2000000.00, 'Estados Unidos', NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (12, 'Sophia',    'König',              900000.00, 'Alemania',       NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (13, 'Diego',     'Fuentes Álvarez',    400000.00, 'Argentina',      NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (14, 'Yuki',      'Nakamura',           300000.00, 'Japón',          NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (15, 'Michael',   'Brennan',           1100000.00, 'Irlanda',        NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (16, 'Aisha',     'Diallo',             250000.00, 'Senegal',        NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (17, 'Carlos',    'Herrera Pinto',      650000.00, 'Colombia',       NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (18, 'Natasha',   'Volkov',             700000.00, 'Rusia',          NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (19, 'Ben',       'Harrison',           850000.00, 'Australia',      NULL);
INSERT INTO peliculas.actores (idactor, nombre, apellidos, salario_mes_rodaje, pais_nacimiento, observaciones) VALUES (20, 'Lin',       'Wei Zhang',          500000.00, 'China',          NULL);

-- ============================================================
--  INSERTS: PELÍCULAS 
-- ============================================================

INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (1,  'Horizonte Final',          1,  TO_DATE('15/07/2019','DD/MM/YYYY'), 'Estados Unidos', 128, 420000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (2,  'La Última Oportunidad',    3,  TO_DATE('22/02/2020','DD/MM/YYYY'), 'España', 112,  22000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (3,  'Código Rojo',              7,  TO_DATE('05/11/2020','DD/MM/YYYY'), 'Francia', 118,  95000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (4,  'Más Allá del Tiempo',      4,  TO_DATE('18/03/2021','DD/MM/YYYY'), 'Estados Unidos', 145, 580000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (5,  'El Gran Enredo',           2,  TO_DATE('30/04/2021','DD/MM/YYYY'), 'España', 95,  18000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (6,  'Océano Profundo',          9,  TO_DATE('10/06/2021','DD/MM/YYYY'), 'Australia', 132, 310000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (7,  'Sombras en la Niebla',     5,  TO_DATE('29/10/2021','DD/MM/YYYY'), 'Japón', 105,  38000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (8,  'Vuelta a Casa',            8,  TO_DATE('14/02/2022','DD/MM/YYYY'), 'Italia', 108,  27000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (9,  'El Último Detective',      7,  TO_DATE('20/05/2022','DD/MM/YYYY'), 'Reino Unido', 122,  88000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (10, 'Pequeños Gigantes',        6,  TO_DATE('22/07/2022','DD/MM/YYYY'), 'Estados Unidos', 98, 650000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (11, 'Noche Sin Fin',            5,  TO_DATE('28/10/2022','DD/MM/YYYY'), 'Alemania', 110,  42000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (12, 'La Conspiración',          7,  TO_DATE('12/01/2023','DD/MM/YYYY'), 'Estados Unidos', 135, 195000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (13, 'Amor en Lisboa',           8,  TO_DATE('10/03/2023','DD/MM/YYYY'), 'Portugal', 102,  11000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (14, 'Revolución Digital',       4,  TO_DATE('21/07/2023','DD/MM/YYYY'), 'Corea del Sur', 140, 280000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (15, 'Caminos Cruzados',         3,  TO_DATE('03/11/2023','DD/MM/YYYY'), 'Argentina', 118,  15000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (16, 'Velocidad Máxima',         1,  TO_DATE('28/06/2024','DD/MM/YYYY'), 'Estados Unidos', 120, 175000000.00);
INSERT INTO peliculas.pelicula (idpelicula, nombre, idgenero, fecha_estreno, pais, duracion, recaudacion) VALUES (17, 'El Señor de los Sueños',   4,  TO_DATE('15/11/2024','DD/MM/YYYY'), 'China', 150,        NULL);

-- ============================================================
--  INSERTS: REPARTO 
-- ============================================================

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (1,  1,  'principal', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (1,  2,  'principal', 7);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (1,  11, 'secundario', 3);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (1,  19, 'secundario', 5);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (2,  3,  'principal', 7);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (2,  4,  'principal', 4);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (2,  13, 'secundario', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (3,  6,  'principal', 3);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (3,  10, 'secundario', 2);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (3,  15, 'cameo', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (4,  11, 'principal', 5);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (4,  1,  'secundario', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (4,  2,  'secundario', 25);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (4,  20, 'cameo', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (5,  3,  'principal', 4);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (5,  4,  'secundario', 2);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (5,  8,  'secundario', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (6,  19, 'principal', 9);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (6,  10, 'secundario', 1);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (6,  9,  'cameo', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (7,  7,  'principal', 8);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (7,  14, 'principal', 12);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (7,  20, 'secundario', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (8,  5,  'principal', 9);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (8,  6,  'secundario', 5);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (8,  8,  'cameo', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (9,  15, 'principal', 8);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (9,  10, 'secundario', 8);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (9,  18, 'cameo', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (10, 11, 'principal', 3);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (10, 2,  'secundario', 3);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (10, 8,  'cameo', 3);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (11, 12, 'principal', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (11, 18, 'secundario', 2);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (11, 16, 'cameo', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (12, 1,  'principal',9);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (12, 11, 'secundario', 1);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (12, 15, 'secundario', 1);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (12, 2,  'cameo', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (13, 5,  'principal', 11);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (13, 13, 'secundario', 9);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (13, 6,  'cameo', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (14, 20, 'principal', 4);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (14, 7,  'secundario', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (14, 14, 'cameo', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (15, 13, 'principal',8);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (15, 17, 'secundario', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (15, 16, 'cameo', 2);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (16, 1,  'principal', 4);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (16, 2,  'principal', 3);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (16, 19, 'secundario', 2);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (16, 9,  'cameo', 1);

INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (17, 20, 'principal', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (17, 7,  'secundario', 6);
INSERT INTO peliculas.reparto (idpelicula, idactor, papel, meses_rodaje) VALUES (17, 12, 'cameo', 1);

COMMIT;
-- ============================================================
--  FIN DEL SCRIPT
-- ============================================================

