version: "3.8"

services:
  web:
    image: php:8.3-apache
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: app_db
      DB_USER: admin
      DB_PASS: 123

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
