INSERT INTO DEPARTAMENTO
(CODEP, CODEMDIR, CODDEPDEP, CODCEN, NOMDEP, PREANU, TIDIR)
VALUES ('VENZN', NULL, 'DIRGE', 'DIGE', 'Ventas zona norte', 8250000, 'F');

select * from DEPARTAMENTO;

drop user empresa;

CREATE USER empresa IDENTIFIED BY 123
               QUOTA UNLIMITED ON USERS;
GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO empresa;