CREATE TABLE productos(
cod_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_producto VARCHAR2(50 CHAR) NOT NULL,
precio NUMBER(6,2) CHECK (precio > 0) NOT NULL,
stock NUMBER(4) CHECK (stock > 0)
);

CREATE TABLE clientes (
dni VARCHAR2(9 CHAR) PRIMARY KEY,
nombre VARCHAR2(40 CHAR) NOT NULL,
email VARCHAR2(100 CHAR) NOT NULL UNIQUE,
fecha_registro DATE DEFAULT SYSDATE,
activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')) 
);

CREATE TABLE cursos (
id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY,
nombre_curso VARCHAR2(80 CHAR) UNIQUE NOT NULL,
duracion_horas NUMBER(3) CHECK (DURACION_HORAS BETWEEN 10 AND 200),
nivel VARCHAR2(15 CHAR) CHECK (nivel IN ('Basico','Intermedio','Avanzado')),
precio NUMBER(4,2) CHECK (precio > 50)  
);




-- 1. Muestra el nombre de todos los países de la tabla COUNTRY.
SELECT name FROM COUNTRY c ;

-- 2. Muestra el código y el nombre de todas los países de la tabla COUNTRY.
SELECT name, code2 FROM country;

-- 3. Muestra la código, el nombre, la población y la población en 2050 (suponemos que la
-- población en 2050 es un 30% mayor que la de la tabla, esto es multiplicar population
-- por 1.30) y pon a las columnas los alias: CODIGO, NOMBRE,POBLACION y
-- POBLACION_2050.
SELECT code2 AS codigo, name AS nombre, population AS poblacion, (population * 1.30) as POBLACION_2050 FROM COUNTRY; 

-- 4. De la tabla COUNTRY saca el nombre del país todo en minúsculas y el continente todo
-- en mayúsculas. A la columna nombre ponle el alias nombre_minus y a la segunda
-- continente_mayus.
SELECT lower(name) AS nombre_minus, upper(continent) AS continente_mayus FROM COUNTRY;

-- 5. Muestra en una columna el nombre de los países y en otra los 4 primeros caracteres del
-- nombre, usando el alias Codigo_Pais.
SELECT name, substr(name,1,4) AS  codigo_pais FROM COUNTRY;

-- 6. Muestra en una columna el nombre de los países y en otra los 4 últimos caracteres del
-- nombre, usando el alias Codigo_Pais.
SELECT name, substr(name, -4) AS codigo_pais FROM country;

-- 7. Muestra un listado con el nombre de los países y la esperanza de vida.
SELECT name, c.LIFEEXPECTANCY  FROM COUNTRY c ;

-- 8. Muestra un listado con el nombre de los países y la esperanza de vida. Redondea el
--campo esperanza de vida sin decimales. Pon un alias a la columna calculada.
SELECT c.name, ROUND(c.LIFEEXPECTANCY)  AS esperanza_de_vida FROM COUNTRY c; 

-- 9. Muestra un listado con el nombre de los países y la esperanza de vida. Trunca el campo
--esperanza de vida sin decimales. Pon un alias a la columna calculada.
SELECT c.NAME AS pais, TRUNC(c.LIFEEXPECTANCY ) AS esperanza_de_vida FROM COUNTRY c ;

--10. Muestra las formas de gobierno que hay en los países de la tabla COUNTRY.
SELECT c.GOVERNMENTFORM  FROM COUNTRY c ;

--11. Muestra las distintas formas de gobierno que hay en los países de la tabla COUNTRY.
SELECT distinct c.GOVERNMENTFORM  FROM COUNTRY c; 

--12. Muestra el nombre de los países ordenados de forma ascendente.
SELECT c.NAME FROM COUNTRY c ORDER BY c.NAME asc;

--13. Muestra el nombre de los países ordenados de forma descendente.
SELECT c.NAME FROM COUNTRY c ORDER BY c.NAME desc;

--14. Muestra los registros de la tabla COUNTRY ordenados por continente de forma
--ascendente y luego por población de forma descendente.
SELECT * FROM COUNTRY c ORDER BY c.CONTINENT ASC, c.POPULATION DESC;

--15. Muestra una lista con las 5 primeras filas de la tabla COUNTRY (ROWNUM)
SELECT * FROM COUNTRY c WHERE rownum <= 5;

--16. Muestra todos los países que tienen como forma de gobierno república (Republic)
SELECT * FROM COUNTRY c WHERE lower(GOVERNMENTFORM) = 'republic';

--17. Muestra todos los países del continente Asia.
SELECT * FROM COUNTRY c WHERE c.CONTINENT = 'Asia';

--18. Muestra todas las ciudades (tabla CITY) que tiene el país Argentina.
SELECT code FROM country WHERE name = 'Argentina';
SELECT * FROM city WHERE COUNTRYCODE = 'ARG';

--19. Muestra todos los países con una superficie mayor de 100.000 km. Ordenalos por
--superficie descendente.
SELECT * FROM COUNTRY c WHERE c.SURFACEAREA > 100000 ORDER BY c.SURFACEAREA DESC; 

--20. Muestra todos los países con una superficie menor de 50.000 km. Ordenalos por
--superficie descendente.
SELECT * FROM COUNTRY c WHERE c.SURFACEAREA < 50000 ORDER BY c.SURFACEAREA DESC;

--21. Muestra todos los países con una superficie entre 50.000 y 100.000 km. Ordenalos
--por superficie descendente. Si puedes, hazlo de 2 formas distintas..
SELECT * FROM COUNTRY c WHERE c.SURFACEAREA > 50000 AND c.SURFACEAREA < 100000 ORDER BY c.SURFACEAREA DESC;
SELECT * FROM COUNTRY c WHERE c.SURFACEAREA BETWEEN 50000 AND 100000 ORDER BY c.SURFACEAREA DESC;

--22. Muestra todos los países de Europa, Asia y África. Si puedes, hazlo de 2 formas
--distintas.
SELECT * FROM COUNTRY c WHERE c.CONTINENT  = 'Europa' OR  c.CONTINENT = 'Asia' OR  c.CONTINENT = 'Africa';
SELECT * FROM COUNTRY c WHERE c.CONTINENT IN ('Europa','Asia','Africa');

--23. Muestra todos los países cuyo nombre empieza por A.
SELECT * FROM COUNTRY c WHERE SUBSTR(c.NAME ,1,1) = 'A';

--24. Muestra todos los países cuyo nombre empieza por vocal.
SELECT * FROM country WHERE name LIKE 'A%' 
OR name LIKE 'E%'
OR name LIKE 'I%'
OR name LIKE 'O%'
OR name LIKE 'U%';

SELECT * FROM country WHERE substr(name,1,1) IN ('A','E','I','O','U');

--25. Muestra todos los países cuyo nombre empieza por Ar.
SELECT * FROM COUNTRY c WHERE SUBSTR(c.NAME ,1,2) = 'Ar';
SELECT * FROM country WHERE name LIKE 'Ar%';

--26. Muestra los países cuyo nombre contenga las letras ar (da igual si la a o la r están en
--mayúsculas o minúsculas, deben salir todas)
SELECT * FROM COUNTRY c WHERE INSTR(upper(c.NAME), 'A') > 0 OR INSTR(upper(c.NAME), 'R') > 0;

--27. Muestra las países cuyo nombre acabe en IN
SELECT * FROM COUNTRY c WHERE SUBSTR(upper(c.NAME),-2) = 'IN';  
SELECT * FROM COUNTRY c WHERE UPPER(c.NAME) LIKE '%IN';




