
CREATE TABLE AJEDREZ.PARTICIPANTES(
  NUM_ASOCIADO   NUMBER(3),
  NOMBRE         VARCHAR2(15),
  DIRECCION      VARCHAR2(20),
  TELF           VARCHAR2(9),
  CAMPEONATOS    NUMBER(3),
  PAIS           NUMBER(3),
  TIPO           VARCHAR2(7) CHECK (TIPO IN ('JUGADOR', 'ARBITRO')),
 CONSTRAINT PK_PARTICIPANTES PRIMARY KEY (NUM_ASOCIADO) 
);

CREATE TABLE AJEDREZ.JUGADORES(
  N_ASOCIADO     NUMBER(3),
  NIVEL          NUMBER(2) CHECK (NIVEL BETWEEN 1 AND 10),
 CONSTRAINT PK_JUGADORES PRIMARY KEY (N_ASOCIADO)
);

CREATE TABLE AJEDREZ.PAISES(
  NUM_PAIS       		NUMBER(3),
  NOMBRE         		VARCHAR2(15),
  NUM_CLUBES     		NUMBER(2),
  PAIS_Q_LO_REPRESENTA  NUMBER(3),
 CONSTRAINT PK_PAISES PRIMARY KEY (NUM_PAIS)
 );

CREATE TABLE AJEDREZ.ALOJAMIENTOS(
  PARTICIPANTE   NUMBER(3),
  HOTEL   	 VARCHAR2(15),
  FECHAIN          DATE,
  FECHAOUT          DATE,
 CONSTRAINT PK_ALOJAMIENTOS PRIMARY KEY (PARTICIPANTE,HOTEL)
);

CREATE TABLE AJEDREZ.PARTIDAS(
  COD_PARTIDA    NUMBER(3),
  ARBITRO        NUMBER(3),
  SALA           NUMBER(3),
  FECHA          DATE,
  GANADOR	     NUMBER(3),
  ENTRADAS       NUMBER(4),
 CONSTRAINT PK_PARTIDAS PRIMARY KEY (COD_PARTIDA)
);
 
CREATE TABLE AJEDREZ.CONTRINCANTES(
  PARTIDA       NUMBER(3),
  JUGADOR       NUMBER(3),
  COLOR         VARCHAR2(8) CHECK (COLOR IN ('BLANCAS', 'NEGRAS')),
 CONSTRAINT PK_CONTRINCANTES PRIMARY KEY (PARTIDA,JUGADOR)
);
 
CREATE TABLE AJEDREZ.MOVIMIENTOS(
  PARTIDA		 NUMBER(3),
  NUM_ORDEN      NUMBER(3),
  JUGADA		 VARCHAR2(10),
  COMENTARIO     VARCHAR2(50),
 CONSTRAINT PK_MOVIMIENTOS PRIMARY KEY (PARTIDA,NUM_ORDEN)
 );
 
CREATE TABLE AJEDREZ.HOTELES(
  NOMBRE         VARCHAR2(20),
  DIRECCION      VARCHAR2(30),
  TELEFONO       VARCHAR2(9),
 CONSTRAINT PK_HOTELES PRIMARY KEY (NOMBRE)
);
 
CREATE TABLE AJEDREZ.SALAS(
  COD_SALA       NUMBER(3),
  CAPACIDAD      NUMBER(4),
  MEDIOS         VARCHAR(10),
  HOTEL          VARCHAR2(20),
 CONSTRAINT PK_SALAS PRIMARY KEY (COD_SALA)
);
 

-----------------------------------------------------------------------------------------
-------     RELACIONES ENTRE LAS TABLAS    ----------------------------------------------  
-----------------------------------------------------------------------------------------

ALTER TABLE AJEDREZ.PARTICIPANTES 
    ADD CONSTRAINT FK_PARTIC_PAIS FOREIGN KEY (PAIS) REFERENCES AJEDREZ.PAISES;

ALTER TABLE AJEDREZ.JUGADORES 
    ADD CONSTRAINT FK_JUGADOR_PARTIC FOREIGN KEY (N_ASOCIADO) REFERENCES AJEDREZ.PARTICIPANTES;
    
ALTER TABLE AJEDREZ.ALOJAMIENTOS
    ADD CONSTRAINT FK_ALOJ_PARTIC FOREIGN KEY (PARTICIPANTE) REFERENCES AJEDREZ.PARTICIPANTES
	ADD CONSTRAINT FK_ALOJ_HOTEL FOREIGN KEY (HOTEL) REFERENCES AJEDREZ.HOTELES;
	
ALTER TABLE AJEDREZ.PAISES
    ADD CONSTRAINT FK_PAIS_PAIS FOREIGN KEY (PAIS_Q_LO_REPRESENTA)REFERENCES AJEDREZ.PAISES;

ALTER TABLE AJEDREZ.CONTRINCANTES
    ADD CONSTRAINT FK_CONTRIN_PARTIDA FOREIGN KEY (PARTIDA) REFERENCES AJEDREZ.PARTIDAS
    ADD CONSTRAINT FK_CONTRIN_JUGADOR FOREIGN KEY (JUGADOR) REFERENCES AJEDREZ.JUGADORES;
   
ALTER TABLE AJEDREZ.MOVIMIENTOS
	ADD CONSTRAINT FK_MOV_PARTIDA FOREIGN KEY (PARTIDA) REFERENCES AJEDREZ.PARTIDAS;
	
ALTER TABLE AJEDREZ.PARTIDAS
	ADD CONSTRAINT FK_PARTIDA_ARBITRO FOREIGN KEY (ARBITRO) REFERENCES AJEDREZ.PARTICIPANTES
	ADD CONSTRAINT FK_PARTIDA_GANADOR FOREIGN KEY (GANADOR) REFERENCES AJEDREZ.JUGADORES
	ADD CONSTRAINT FK_PARTIDA_SALA FOREIGN KEY (SALA) REFERENCES AJEDREZ.SALAS;
	
ALTER TABLE AJEDREZ.SALAS
	ADD CONSTRAINT FK_SALA_HOTEL FOREIGN KEY (HOTEL) REFERENCES AJEDREZ.HOTELES;


--------------------------------------------------------------------------------------------
-----  INSERCION DE DATOS    ---------------------------------------------------------------
--------------------------------------------------------------------------------------------
INSERT INTO AJEDREZ.HOTELES VALUES ('HOTEL 1', 'C/CAOBA, 1', '928765567');
INSERT INTO AJEDREZ.HOTELES VALUES ('HOTEL 2', 'C/EMBAJADORES, 104', '912344422');
INSERT INTO AJEDREZ.HOTELES VALUES ('HOTEL 3', 'PASEO DE LAS ACACIAS, 24', '919089738');
INSERT INTO AJEDREZ.HOTELES VALUES ('HOTEL 4', 'PLAZA TOLEDO, 4', '917789950');

INSERT INTO AJEDREZ.SALAS VALUES (100,200,'TV','HOTEL 1'); 
INSERT INTO AJEDREZ.SALAS VALUES (101,150,'VIDEO','HOTEL 1'); 
INSERT INTO AJEDREZ.SALAS VALUES (102,90,'TV','HOTEL 1'); 
INSERT INTO AJEDREZ.SALAS VALUES (103,230,'TV Y VIDEO','HOTEL 1'); 
INSERT INTO AJEDREZ.SALAS VALUES (200,500,'TV Y VIDEO','HOTEL 2'); 
INSERT INTO AJEDREZ.SALAS VALUES (201,1000,NULL,'HOTEL 2'); 
INSERT INTO AJEDREZ.SALAS VALUES (202,80,'VIDEO','HOTEL 2'); 
INSERT INTO AJEDREZ.SALAS VALUES (300,240,'VIDEO','HOTEL 3'); 
INSERT INTO AJEDREZ.SALAS VALUES (401,120,'TV','HOTEL 4'); 
 
INSERT INTO AJEDREZ.PAISES VALUES (1,'SUECIA',2,NULL);
INSERT INTO AJEDREZ.PAISES VALUES (2,'NORUEGA',3,NULL);
INSERT INTO AJEDREZ.PAISES VALUES (3,'ISLANDIA',1,1);
INSERT INTO AJEDREZ.PAISES VALUES (4,'ALEMANIA',8,NULL);
INSERT INTO AJEDREZ.PAISES VALUES (5,'FRANCIA',10,NULL);
INSERT INTO AJEDREZ.PAISES VALUES (8,'AUSTRIA',4,NULL);
INSERT INTO AJEDREZ.PAISES VALUES (6,'SUIZA',2,8);
INSERT INTO AJEDREZ.PAISES VALUES (7,'ITALIA',12,NULL);


INSERT INTO AJEDREZ.PARTICIPANTES VALUES (1,'PEPE MARTIN','C/LEGANITOS, 23','912340909',0,1,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (2,'JUAN MARTIN','C/LEGANITOS, 23','912340909',1,1,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (4,'FERMIN PEREZ','C/ALCALA, 387','915459900',0,2,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (5,'ENRIQUE LOPEZ','C/AVE MARIA, 6','914567676',1,2,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (7,'GENOVEVA PEREZ','C/ALCALA, 64','923465567',0,4,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (8,'MARIO JIMENEZ','C/GRAN VIA, 31','928999876',0,4,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (10,'ANA SANCHEZ','PZA. ESPANIA, 2','929557845',0,4,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (11,'JAIME GONZALEZ','C/HERRERA ORIA, 34','939822545',0,5,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (12,'CARY LAPIQUE','C/VALVERDE, 89','931876005',0,5,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (14,'RAUL SANCHEZ','C/MONTERA, 24','934886545',0,5,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (15,'GENARO MORAN','C/CARRETAS, 9','935878945',0,5,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (16,'MAR ALVAREZ','C/MORGENS, 45','943356739',1,3,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (17,'JOSE MARTINEZ','C/ABENDS, 18','946898796',0,3,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (19,'MARTIN ALVAREZ','C/HERBST, 12','959476545',2,6,'JUGADOR'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (20,'AGAR LOPEZ','C/RINCONETE, 109','952576545',3,6,'JUGADOR'); 

INSERT INTO AJEDREZ.PARTICIPANTES VALUES (3,'ANA LOPEZ','C/CASCORRO, 3','919876545',0,2,'ARBITRO'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (6,'MARIA FERNANDEZ','C/VALENCIA, 7','928765434',0,4,'ARBITRO'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (9,'LUISA SANCHEZ','C/GRAN VIA, 56','929869655',0,4,'ARBITRO'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (13,'ESTRELLA GENIL','C/DEL PEZ, 4','932806545',0,5,'ARBITRO'); 
INSERT INTO AJEDREZ.PARTICIPANTES VALUES (18,'SILVIA JIMENEZ','C/STURM, 33','957076545',0,6,'ARBITRO'); 

INSERT INTO AJEDREZ.JUGADORES VALUES (1,5);
INSERT INTO AJEDREZ.JUGADORES VALUES (2,9);
INSERT INTO AJEDREZ.JUGADORES VALUES (4,3);
INSERT INTO AJEDREZ.JUGADORES VALUES (5,8);
INSERT INTO AJEDREZ.JUGADORES VALUES (7,2);
INSERT INTO AJEDREZ.JUGADORES VALUES (8,1);
INSERT INTO AJEDREZ.JUGADORES VALUES (10,4);
INSERT INTO AJEDREZ.JUGADORES VALUES (11,6);
INSERT INTO AJEDREZ.JUGADORES VALUES (12,2);
INSERT INTO AJEDREZ.JUGADORES VALUES (14,1);
INSERT INTO AJEDREZ.JUGADORES VALUES (15,7);
INSERT INTO AJEDREZ.JUGADORES VALUES (16,7);
INSERT INTO AJEDREZ.JUGADORES VALUES (17,9);
INSERT INTO AJEDREZ.JUGADORES VALUES (19,4);
INSERT INTO AJEDREZ.JUGADORES VALUES (20,1);


INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (1,'HOTEL 1',to_date('23/04/2007','dd/mm/yyyy'),to_date('24/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (2,'HOTEL 1',to_date('22/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (3,'HOTEL 1',to_date('22/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (4,'HOTEL 2',to_date('23/04/2007','dd/mm/yyyy'),to_date('24/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (5,'HOTEL 2',to_date('24/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (6,'HOTEL 2',to_date('24/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (7,'HOTEL 2',to_date('22/04/2007','dd/mm/yyyy'),to_date('23/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (8,'HOTEL 2',to_date('23/04/2007','dd/mm/yyyy'),to_date('24/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (9,'HOTEL 3',to_date('23/04/2007','dd/mm/yyyy'),to_date('26/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (10,'HOTEL 3',to_date('23/04/2007','dd/mm/yyyy'),to_date('26/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (11,'HOTEL 3',to_date('24/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (12,'HOTEL 2',to_date('22/04/2007','dd/mm/yyyy'),to_date('23/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (13,'HOTEL 2',to_date('23/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (14,'HOTEL 2',to_date('21/04/2007','dd/mm/yyyy'),to_date('24/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (15,'HOTEL 1',to_date('21/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (16,'HOTEL 2',to_date('22/04/2007','dd/mm/yyyy'),to_date('24/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (17,'HOTEL 1',to_date('23/04/2007','dd/mm/yyyy'),to_date('26/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (18,'HOTEL 2',to_date('24/04/2007','dd/mm/yyyy'),to_date('24/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (19,'HOTEL 3',to_date('23/04/2007','dd/mm/yyyy'),to_date('25/04/2007','dd/mm/yyyy')); 
INSERT INTO AJEDREZ.ALOJAMIENTOS VALUES (20,'HOTEL 1',to_date('24/04/2007','dd/mm/yyyy'),to_date('26/04/2007','dd/mm/yyyy')); 

INSERT INTO AJEDREZ.PARTIDAS VALUES (1,3,100,to_date('22/04/2007','dd/mm/yyyy'),1,30);
INSERT INTO AJEDREZ.PARTIDAS VALUES (2,6,101,to_date('22/04/2007','dd/mm/yyyy'),10,15);
INSERT INTO AJEDREZ.PARTIDAS VALUES (3,9,102,to_date('23/04/2007','dd/mm/yyyy'),NULL,59);
INSERT INTO AJEDREZ.PARTIDAS VALUES (4,13,103,to_date('24/04/2007','dd/mm/yyyy'),4,60);
INSERT INTO AJEDREZ.PARTIDAS VALUES (5,18,200,to_date('22/04/2007','dd/mm/yyyy'),20,40);
INSERT INTO AJEDREZ.PARTIDAS VALUES (6,3,201,to_date('22/04/2007','dd/mm/yyyy'),5,28);
INSERT INTO AJEDREZ.PARTIDAS VALUES (7,6,202,to_date('22/04/2007','dd/mm/yyyy'),1,12);
INSERT INTO AJEDREZ.PARTIDAS VALUES (8,9,300,to_date('23/04/2007','dd/mm/yyyy'),17,19);
INSERT INTO AJEDREZ.PARTIDAS VALUES (9,13,401,to_date('23/04/2007','dd/mm/yyyy'),8,5);
INSERT INTO AJEDREZ.PARTIDAS VALUES (10,18,100,to_date('23/04/2007','dd/mm/yyyy'),5,70);
INSERT INTO AJEDREZ.PARTIDAS VALUES (11,3,101,to_date('24/04/2007','dd/mm/yyyy'),NULL,45);
INSERT INTO AJEDREZ.PARTIDAS VALUES (12,6,102,to_date('23/04/2007','dd/mm/yyyy'),4,63);
INSERT INTO AJEDREZ.PARTIDAS VALUES (13,9,201,to_date('22/04/2007','dd/mm/yyyy'),20,27);
INSERT INTO AJEDREZ.PARTIDAS VALUES (14,13,300,to_date('22/04/2007','dd/mm/yyyy'),2,18);
INSERT INTO AJEDREZ.PARTIDAS VALUES (15,18,401,to_date('24/04/2007','dd/mm/yyyy'),14,30);

INSERT INTO AJEDREZ.CONTRINCANTES VALUES (1,1,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (1,8,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (2,2,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (2,10,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (3,12,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (3,7,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (4,11,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (4,4,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (5,19,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (5,20,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (6,15,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (6,5,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (7,19,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (7,1,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (8,4,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (8,17,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (9,16,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (9,8,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (10,11,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (10,5,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (11,12,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (11,7,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (12,19,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (12,4,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (13,15,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (13,20,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (14,20,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (14,2,'NEGRAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (15,19,'BLANCAS');
INSERT INTO AJEDREZ.CONTRINCANTES VALUES (15,14,'NEGRAS');

INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (1,1,'P3x4Q','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (1,2,'C4EnrrK','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (1,3,'A5xT2',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (1,4,'A8JM','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (2,1,'P5xT9','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (2,2,'P2EnrrK','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (2,3,'P1xT4','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (3,1,'P3xP6','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (3,2,'C1xA7','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (3,3,'A2xT1',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (3,4,'P2xK7','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (4,1,'P1xP5','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (4,2,'C3xQ2','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (4,3,'P1xT5',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (4,4,'A3xT6',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (4,5,'P3xQ2','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (10,1,'P4xP6','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (10,2,'C4EnrrK','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (10,3,'P1xT9',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (10,4,'A1JqQ','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (5,1,'P3x4Q','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (5,2,'T3xA7','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (6,1,'P1xP5','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (6,2,'P2xP6',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (6,3,'T4xA1',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (6,4,'K2xK1','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (7,1,'P2xP5','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (7,2,'C4EnrrT1','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (8,1,'C3xQ1','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (8,2,'P5xp4','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (9,1,'P3x4Q','comienza partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (9,2,'Q1JqQ2','Menudo jugadon');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (9,3,'T1ErrK2',NULL);
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (9,4,'Q1JqK4','fin de partida');
INSERT INTO AJEDREZ.MOVIMIENTOS VALUES (11,1,NULL,'NEGRAS NO PRESENTADO');

COMMIT;

