/*
--------------------------------------------------------------------
Script de inserción de datos para BikeStores - Oracle SQL
--------------------------------------------------------------------
*/

-- Modificar las tablas para permitir inserción manual de IDs
ALTER TABLE sales.categories MODIFY category_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE sales.brands MODIFY brand_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE sales.products MODIFY product_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE sales.customers MODIFY customer_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE sales.stores MODIFY store_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE sales.staffs MODIFY staff_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE sales.orders MODIFY order_id GENERATED BY DEFAULT ON NULL AS IDENTITY;

-- ============================================
-- INSERTAR CATEGORÍAS
-- ============================================
INSERT ALL
  INTO sales.categories (category_id, category_name) VALUES (1, 'Children Bicycles')
  INTO sales.categories (category_id, category_name) VALUES (2, 'Comfort Bicycles')
  INTO sales.categories (category_id, category_name) VALUES (3, 'Cruisers Bicycles')
  INTO sales.categories (category_id, category_name) VALUES (4, 'Cyclocross Bicycles')
  INTO sales.categories (category_id, category_name) VALUES (5, 'Electric Bikes')
  INTO sales.categories (category_id, category_name) VALUES (6, 'Mountain Bikes')
  INTO sales.categories (category_id, category_name) VALUES (7, 'Road Bikes')
SELECT * FROM dual;

-- ============================================
-- INSERTAR MARCAS
-- ============================================
INSERT ALL
  INTO sales.brands (brand_id, brand_name) VALUES (1, 'Electra')
  INTO sales.brands (brand_id, brand_name) VALUES (2, 'Haro')
  INTO sales.brands (brand_id, brand_name) VALUES (3, 'Heller')
  INTO sales.brands (brand_id, brand_name) VALUES (4, 'Pure Cycles')
  INTO sales.brands (brand_id, brand_name) VALUES (5, 'Ritchey')
  INTO sales.brands (brand_id, brand_name) VALUES (6, 'Strider')
  INTO sales.brands (brand_id, brand_name) VALUES (7, 'Sun Bicycles')
  INTO sales.brands (brand_id, brand_name) VALUES (8, 'Surly')
  INTO sales.brands (brand_id, brand_name) VALUES (9, 'Trek')
SELECT * FROM dual;

-- ============================================
-- INSERTAR PRODUCTOS (muestra parcial)
-- ============================================
INSERT ALL
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (1, 'Trek 820 - 2016', 9, 6, 2016, 379.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (2, 'Ritchey Timberwolf Frameset - 2016', 5, 6, 2016, 749.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (3, 'Surly Wednesday Frameset - 2016', 8, 6, 2016, 999.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (4, 'Trek Fuel EX 8 29 - 2016', 9, 6, 2016, 2899.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (5, 'Heller Shagamaw Frame - 2016', 3, 6, 2016, 1320.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (6, 'Surly Ice Cream Truck Frameset - 2016', 8, 6, 2016, 469.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (7, 'Trek Slash 8 27.5 - 2016', 9, 6, 2016, 3999.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (8, 'Trek Remedy 29 Carbon Frameset - 2016', 9, 6, 2016, 1799.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (9, 'Trek Conduit+ - 2016', 9, 5, 2016, 2999.99)
  INTO sales.products (product_id, product_name, brand_id, category_id, model_year, list_price) 
    VALUES (10, 'Surly Straggler - 2016', 8, 4, 2016, 1549)
SELECT * FROM dual;

-- ============================================
-- INSERTAR TIENDAS
-- ============================================
INSERT ALL
  INTO sales.stores (store_id, store_name, phone, email, street, city, state, zip_code)
    VALUES (1, 'Santa Cruz Bikes', '(831) 476-4321', 'santacruz@bikes.shop', '3700 Portola Drive', 'Santa Cruz', 'CA', '95062')
  INTO sales.stores (store_id, store_name, phone, email, street, city, state, zip_code)
    VALUES (2, 'Baldwin Bikes', '(516) 379-8888', 'baldwin@bikes.shop', '4200 Chestnut Lane', 'Baldwin', 'NY', '11432')
  INTO sales.stores (store_id, store_name, phone, email, street, city, state, zip_code)
    VALUES (3, 'Rowlett Bikes', '(972) 530-5555', 'rowlett@bikes.shop', '8000 Fairway Avenue', 'Rowlett', 'TX', '75088')
SELECT * FROM dual;

-- ============================================
-- INSERTAR PERSONAL (STAFFS)
-- ============================================
INSERT ALL
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (1, 'Fabiola', 'Jackson', 'fabiola.jackson@bikes.shop', '(831) 555-5554', 1, 1, NULL)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (2, 'Mireya', 'Copeland', 'mireya.copeland@bikes.shop', '(831) 555-5555', 1, 1, 1)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (3, 'Genna', 'Serrano', 'genna.serrano@bikes.shop', '(831) 555-5556', 1, 1, 2)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (4, 'Virgie', 'Wiggins', 'virgie.wiggins@bikes.shop', '(831) 555-5557', 1, 1, 2)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (5, 'Jannette', 'David', 'jannette.david@bikes.shop', '(516) 379-4444', 1, 2, NULL)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (6, 'Marcelene', 'Boyer', 'marcelene.boyer@bikes.shop', '(516) 379-4445', 1, 2, 5)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (7, 'Venita', 'Daniel', 'venita.daniel@bikes.shop', '(516) 379-4446', 1, 2, 5)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (8, 'Kali', 'Vargas', 'kali.vargas@bikes.shop', '(972) 530-5555', 1, 3, NULL)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (9, 'Layla', 'Terrell', 'layla.terrell@bikes.shop', '(972) 530-5556', 1, 3, 8)
  INTO sales.staffs (staff_id, first_name, last_name, email, phone, active, store_id, manager_id)
    VALUES (10, 'Bernardine', 'Houston', 'bernardine.houston@bikes.shop', '(972) 530-5557', 1, 3, 8)
SELECT * FROM dual;

-- ============================================
-- INSERTAR CLIENTES (muestra parcial)
-- ============================================
INSERT ALL
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (1, 'Debra', 'Burks', NULL, 'debra.burks@yahoo.com', '9273 Thorne Ave.', 'Orchard Park', 'NY', '14127')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (2, 'Kasha', 'Todd', NULL, 'kasha.todd@yahoo.com', '910 Vine Street', 'Campbell', 'CA', '95008')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (3, 'Tameka', 'Fisher', NULL, 'tameka.fisher@aol.com', '769C Honey Creek St.', 'Redondo Beach', 'CA', '90278')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (4, 'Daryl', 'Spence', '(308) 555-0100', 'daryl.spence@aol.com', '988 Pearl Lane', 'Uniondale', 'NY', '11553')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (5, 'Charolette', 'Rice', '(916) 381-6003', 'charolette.rice@msn.com', '107 River Dr.', 'Sacramento', 'CA', '95820')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (6, 'Lyndsey', 'Bean', NULL, 'lyndsey.bean@hotmail.com', '769 West Road', 'Fairport', 'NY', '14450')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (7, 'Latasha', 'Hays', '(716) 986-3359', 'latasha.hays@hotmail.com', '7014 Manor Station Rd.', 'Buffalo', 'NY', '14215')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (8, 'Jacquline', 'Duncan', NULL, 'jacquline.duncan@yahoo.com', '15 Brown St.', 'Jackson Heights', 'NY', '11372')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (9, 'Genoveva', 'Baldwin', '(707) 975-8569', 'genoveva.baldwin@msn.com', '8550 Spruce Drive', 'Port Orange', 'FL', '32019')
  INTO sales.customers (customer_id, first_name, last_name, phone, email, street, city, state, zip_code)
    VALUES (10, 'Pamelia', 'Newman', '(310) 870-1860', 'pamelia.newman@yahoo.com', '476 East Hill Rd.', 'Sylmar', 'CA', '91342')
SELECT * FROM dual;

-- ============================================
-- INSERTAR ÓRDENES (muestra parcial)
-- ============================================
INSERT ALL
  INTO sales.orders (order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id)
    VALUES (1, 1, 4, TO_DATE('2016-01-01', 'YYYY-MM-DD'), TO_DATE('2016-01-03', 'YYYY-MM-DD'), TO_DATE('2016-01-03', 'YYYY-MM-DD'), 1, 2)
  INTO sales.orders (order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id)
    VALUES (2, 2, 4, TO_DATE('2016-01-01', 'YYYY-MM-DD'), TO_DATE('2016-01-04', 'YYYY-MM-DD'), TO_DATE('2016-01-03', 'YYYY-MM-DD'), 1, 2)
  INTO sales.orders (order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id)
    VALUES (3, 3, 4, TO_DATE('2016-01-02', 'YYYY-MM-DD'), TO_DATE('2016-01-05', 'YYYY-MM-DD'), TO_DATE('2016-01-03', 'YYYY-MM-DD'), 2, 6)
  INTO sales.orders (order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id)
    VALUES (4, 4, 4, TO_DATE('2016-01-03', 'YYYY-MM-DD'), TO_DATE('2016-01-04', 'YYYY-MM-DD'), TO_DATE('2016-01-05', 'YYYY-MM-DD'), 2, 6)
  INTO sales.orders (order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id)
    VALUES (5, 5, 4, TO_DATE('2016-01-03', 'YYYY-MM-DD'), TO_DATE('2016-01-06', 'YYYY-MM-DD'), TO_DATE('2016-01-05', 'YYYY-MM-DD'), 1, 2)
SELECT * FROM dual;

-- ============================================
-- INSERTAR ITEMS DE ÓRDENES (muestra parcial)
-- ============================================
INSERT ALL
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (1, 1, 1, 1, 379.99, 0.20)
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (1, 2, 2, 2, 749.99, 0.07)
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (2, 1, 3, 1, 999.99, 0.05)
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (2, 2, 4, 2, 2899.99, 0.05)
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (3, 1, 5, 2, 1320.99, 0.10)
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (4, 1, 6, 1, 469.99, 0.20)
  INTO sales.order_items (order_id, item_id, product_id, quantity, list_price, discount)
    VALUES (5, 1, 7, 2, 3999.99, 0.07)
SELECT * FROM dual;

-- ============================================
-- INSERTAR INVENTARIO (STOCKS - muestra parcial)
-- ============================================
INSERT ALL
  INTO sales.stocks (store_id, product_id, quantity) VALUES (1, 1, 27)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (1, 2, 5)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (1, 3, 6)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (1, 4, 23)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (1, 5, 22)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (2, 1, 30)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (2, 2, 8)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (2, 3, 12)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (3, 1, 15)
  INTO sales.stocks (store_id, product_id, quantity) VALUES (3, 2, 10)
SELECT * FROM dual;

-- Confirmar todas las transacciones
COMMIT;

-- Verificar datos insertados
SELECT 'Categories' AS tabla, COUNT(*) AS registros FROM sales.categories
UNION ALL
SELECT 'Brands', COUNT(*) FROM sales.brands
UNION ALL
SELECT 'Products', COUNT(*) FROM sales.products
UNION ALL
SELECT 'Stores', COUNT(*) FROM sales.stores
UNION ALL
SELECT 'Staffs', COUNT(*) FROM sales.staffs
UNION ALL
SELECT 'Customers', COUNT(*) FROM sales.customers
UNION ALL
SELECT 'Orders', COUNT(*) FROM sales.orders
UNION ALL
SELECT 'Order Items', COUNT(*) FROM sales.order_items
UNION ALL
SELECT 'Stocks', COUNT(*) FROM sales.stocks;