CREATE USER practica IDENTIFIED BY "123";
ALTER USER practica QUOTA UNLIMITED ON USERS;
GRANT VIEW, CONNECT, RESOURCE TO practica;


GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO practica;

--nueva forma
CREATE USER hr_db IDENTIFIED BY "123";

ALTER USER hr_db QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO hr_db;