--1
SELECT 
        AL.NOMBRE || ' ' || AL.APELLIDO,
        AL.FECHA_NACIMIENTO
FROM ALUMNO AL 
;
--2
CREATE OR REPLACE VIEW VISTA_TUTORES AS
SELECT DISTINCT
        P.NOMBRE AS NOMBRE,
        P.APELLIDOS AS APELLIDO,
        CASE 
            WHEN P.COD_PROFESOR = AL.TUTOR
            THEN 'SI' ELSE 'NO'
        END AS TUTOR
FROM PROFESOR P
LEFT JOIN ALUMNO AL ON AL.TUTOR = P.COD_PROFESOR;

--3

SELECT
        CI.NOMBRE AS CICLO,
        MO.NOMBRE AS MODULO,
        P.NOMBRE AS NOMBRE,
        P.APELLIDOS AS APELLIDOS,
        D.NOMBRE AS DEPT
FROM DEPARTAMENTO D 
INNER JOIN PROFESOR P ON D.COD_DEPARTAMENTO = P.COD_DEPARTAMENTO 
INNER JOIN MODULO_IMPARTIDO MOI ON MOI.COD_PROFESOR = P.COD_PROFESOR
INNER JOIN MODULO MO ON MO.COD_MODULO = MOI.COD_MODULO
INNER JOIN CICLO CI ON CI.COD_CICLO = MOI.COD_CICLO
WHERE SUBSTR(P.NOMBRE,1,1) = (
    SELECT SUBSTR(D2.NOMBRE,1,1)
    FROM DEPARTAMENTO D2
    WHERE D2.COD_DEPARTAMENTO = P.COD_DEPARTAMENTO
)
AND MO.HORAS BETWEEN 90 AND 120;
--4
SELECT DISTINCT
        AL.COD_ALUMNO,
        AL.NOMBRE,
        AL.APELLIDOS
FROM ALUMNO AL 
INNER JOIN PROFESOR P ON P.COD_PROFESOR = AL.TUTOR
INNER JOIN MATRICULA M ON M.COD_ALUMNO = AL.COD_ALUMNO
LEFT JOIN DETALLE_MATRICULA DM ON DM.COD_MATRICULA = M.COD_MATRICULA 
WHERE P.COD_DEPARTAMENTO = '003'
AND DM.COD_MODULO NOT IN ('0179');

--5
SELECT 
        M.CURSO_ACADEMICO CURSO,
        COUNT(M.COD_ALUMNO) ALUMNOS,
        COUNT(DISTINCT DM.COD_MODULO) MODULOS,
        ROUND(AVG(DM.NOTA_FINAL),2) NOTA_MEDIA,
        MAX(DM.NOTA_FINAL) NOTA_MAS_ALTA,
        MIN(M.FECHA_MATRICULA) PRIMERA_MATRICULACION
FROM MATRICULA M 
INNER JOIN DETALLE_MATRICULA DM ON DM.COD_MATRICULA = M.COD_MATRICULA
GROUP BY M.CURSO_ACADEMICO;

--6
SELECT 
        P.COD_PROFESOR,
        P.NOMBRE,
        P.APELLIDOS,
        CASE
            WHEN MO.NOMBRE IS NULL 
            THEN 'NO DOCENTE' 
            ELSE MO.NOMBRE 
        END AS MODULO
FROM PROFESOR P 
LEFT JOIN MODULO_IMPARTIDO MOI ON MOI.COD_PROFESOR = P.COD_PROFESOR 
LEFT JOIN MODULO MO ON MO.COD_MODULO = MOI.COD_MODULO
ORDER BY P.APELLIDOS;

--7
SELECT 
        AL.NOMBRE,
        AL.APELLIDOS,
        AL.FECHA_NACIMIENTO,
        AL.DIRECCION,
        SUM(M.IMPORTE), 
        M.CURSO_ACADEMICO --SIN ESTE CAMPO NO ME FUNCIONABA
FROM ALUMNO AL 
INNER JOIN MATRICULA M ON M.COD_ALUMNO = AL.COD_ALUMNO
WHERE TO_CHAR(AL.FECHA_NACIMIENTO,'YYYY') IN ('2006','2004')
AND UPPER(AL.DIRECCION) LIKE '%MA%'
GROUP BY 
        AL.NOMBRE,
        AL.APELLIDOS,
        AL.FECHA_NACIMIENTO,
        AL.DIRECCION,
        M.CURSO_ACADEMICO
HAVING SUM(M.IMPORTE) > 100 AND M.CURSO_ACADEMICO = '2025/2026';

--8

SELECT DISTINCT
        AL.COD_ALUMNO
FROM ALUMNO AL 
INNER JOIN MATRICULA M ON M.COD_ALUMNO = AL.COD_ALUMNO
INNER JOIN DETALLE_MATRICULA DM ON DM.COD_MATRICULA = M.COD_MATRICULA
WHERE AL.COD_ALUMNO = AL.DELEGADO
GROUP BY AL.COD_ALUMNO 
HAVING  AVG(DM.NOTA_FINAL) > 6;



--9

--10
CREATE OR REPLACE VIEW MODULO_EXTENSO AS
SELECT DISTINCT
        CI.NOMBRE CICLO,
        MAX(MO.HORAS) 
FROM CICLO CI 
INNER JOIN MODULO_IMPARTIDO MOI ON MOI.COD_CICLO = CI.COD_CICLO 
INNER JOIN MODULO MO ON MO.COD_MODULO = MOI.COD_MODULO
GROUP BY CI.NOMBRE;

--11
SELECT 
        *
FROM MATRICULA M
WHERE (M.COD_CICLO LIKE 'IFC%'
OR M.COD_CICLO LIKE 'ADGC%')
AND M.CURSO = 1
AND (M.COD_MATRICULA LIKE '%DAW%'
OR M.IMPORTE < 100);
--12
CREATE OR REPLACE VIEW GASTO_POR_ALUMNO AS
SELECT 
        AL.COD_ALUMNO AS COD_ALUMNO,
        AL.NOMBRE AS NOMBRE,
        AL.APELLIDOS AS APELLIDOS, 
        SUM(M.IMPORTE) AS IMPORTE_TOTAL
FROM ALUMNO AL
INNER JOIN MATRICULA M ON AL.COD_ALUMNO = M.COD_ALUMNO
GROUP BY AL.COD_ALUMNO,AL.NOMBRE, AL.APELLIDOS;

--13
SELECT
        AL.COD_ALUMNO,
        AL.NOMBRE
FROM ALUMNO AL 
INNER JOIN MATRICULA M ON M.COD_ALUMNO = AL.COD_ALUMNO 
WHERE (M.CURSO_ACADEMICO = '2024/2025' AND M.CURSO = 1);

--14

