--CREATE TABLE libros (
    isbn CHAR(13) CONSTRAINT pk_libros PRIMARY KEY,
    titulo VARCHAR2(100) CONSTRAINT nn_libros_titulo NOT NULL,
    autor VARCHAR2(200),
    num_paginas NUMBER(5) CONSTRAINT ck_libros_num_paginas CHECK (num_paginas > 0)
);

--CREATE TABLE autores (
    autor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    nacionalidad VARCHAR2(30),
    PRIMARY KEY (autor_id)
);


--ALTER TABLE libros ADD autor_id NUMBER;

--ALTER TABLE libros
ADD CONSTRAINT fk_libros_autor
FOREIGN KEY (autor_id)
REFERENCES autores(autor_id);

--CREATE TABLE empleados (
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    fecha_contratacion DATE DEFAULT SYSDATE NOT NULL,
    salario NUMBER(10,2) CHECK (salario > 1200),
    departamento VARCHAR2(30)
    CHECK (departamento IN ('Ventas', 'Marketing', 'TI', 'Administración'))

);

CREATE TABLE usuarios (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR2(20) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE
);


CREATE TABLE canales (
    canal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_canal VARCHAR2(40) NOT NULL UNIQUE,
    fecha_creacion DATE DEFAULT SYSDATE
);


CREATE TABLE suscripciones (
    usuario_id NUMBER NOT NULL,
    canal_id NUMBER NOT NULL,
    fecha_suscripcion DATE NOT NULL,
    PRIMARY KEY (usuario_id, canal_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(usuario_id),
    FOREIGN KEY (canal_id) REFERENCES canales(canal_id)
);

-- CONSULTA DE NOMBRE DE RESTRICCIONES
SELECT uc.constraint_name, ucc.column_name, uc.search_condition
FROM user_constraints uc
JOIN user_cons_columns ucc ON uc.constraint_name = ucc.constraint_name
WHERE uc.table_name = 'EMPLEADOS'
  AND uc.constraint_type = 'C';

-- eliminar restriccion
ALTER TABLE empleados DROP CONSTRAINT SYS_C008338;

-- nueva columna de telefono
ALTER TABLE empleados ADD telefono VARCHAR2(15);
ALTER TABLE empleados ADD CONSTRAINT un1_telefono UNIQUE (telefono);

-- cambio restriccion salario
ALTER TABLE empleados DROP CONSTRAINT SYS_C008337;
ALTER TABLE empleados ADD CONSTRAINT chk_salario_minimo CHECK (salario > 1350);

ALTER TABLE EMPLEADOS MODIFY nombre varchar2(70);

ALTER TABLE EMPLEADOS DROP COLUMN fecha_contratacion;


CREATE USER libreria IDENTIFIED BY oracle123 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO libreria;

CREATE USER pedidos IDENTIFIED BY oracle123 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO pedidos;

-- ejercicio veterinaria

CREATE USER veterinaria IDENTIFIED BY 123 QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE VIEW TO veterinaria;

CREATE USER admin_pub IDENTIFIED BY 123 quota unlimited ON users;
GRANT CONNECT, resource, CREATE VIEW TO admin_pub;

--- 
CREATE USER prueba_dcl1  IDENTIFIED BY oracle123
DEFAULT TABLESPACE users 
quota 1M ON users;

GRANT CREATE SESSION TO prueba_dcl1;

-- ejercicio dcl
-- 1
CREATE USER prueba_dcl2  IDENTIFIED BY oracle123
DEFAULT TABLESPACE users 
quota 1M ON users;

-- 2
GRANT CONNECT TO prueba_dcl2;
ALTER USER prueba_dcl2 IDENTIFIED BY oracle1234;

CREATE USER academia IDENTIFIED BY 123 quota unlimited ON users;
GRANT CONNECT, resource, CREATE VIEW TO academia;

-- usuario chinook
CREATE USER chinook IDENTIFIED BY oracle123
               QUOTA UNLIMITED ON USERS;

GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO chinook;




