/*
CREATE USER hr IDENTIFIED BY "123";

ALTER USER hr QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, 
CREATE VIEW TO hr;

*/
CREATE USER multas IDENTIFIED BY 123
               QUOTA UNLIMITED ON USERS;
GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO multas;