-- ----------------------------------------------------------------
-- SCRIPT DE BASE DE DATOS 'EMPRESA' (VERSIÓN UNIVERSAL)
-- ----------------------------------------------------------------

-- 1. ELIMINACIÓN DE TABLAS (para empezar de cero)
-- Este bloque PL/SQL usa / como terminador.
-- Debe ejecutarse en "Modo Script" (F5 en SQLDev, Alt+X en DBeaver)

BEGIN
  FOR c IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
-- Descomentar siguiente línea para SQL Developer
--/

-- 2. CREACIÓN DE TABLAS

CREATE TABLE  habilidad  (
   CodHab  CHAR(5) PRIMARY KEY ,
   DesHab  VARCHAR2(30 CHAR) UNIQUE
);

CREATE TABLE  centro  (
  CodCen CHAR(4)  PRIMARY KEY,
  CodEmpDir NUMBER(10) ,
  NomCen VARCHAR2(30 CHAR) NOT NULL UNIQUE,
  DirCen VARCHAR2(50 CHAR) ,
  PobCen VARCHAR2(15 CHAR)
  );

CREATE TABLE  departamento  (
  CodDep CHAR(5) PRIMARY KEY,
  CodEmpDir NUMBER(10),
  CodDepDep CHAR(5 CHAR),
  CodCen CHAR(4),
  NomDep VARCHAR2(40 CHAR) NOT NULL UNIQUE,
  PreAnu NUMBER(12,2),
  TiDir VARCHAR2(1 CHAR) CHECK (TiDir IN ('F','P'))
  );

CREATE TABLE  empleado  (
  CodEmp NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 31) PRIMARY KEY, -- Se ajusta el IDENTITY para empezar después de los inserts manuales
  CodDep CHAR(5),
  ExTelEmp VARCHAR2(9 CHAR),
  FecInEmp DATE,
  FecNaEmp DATE,
  NifEmp VARCHAR2(9 CHAR) UNIQUE,
  NomEmp VARCHAR2(40 CHAR),
  NumHi NUMBER(1) ,
  SalEmp NUMBER(8,2),
  ComEmp NUMBER(6,2)
);

CREATE TABLE  habemp  (
   CodHab  CHAR(5),
   CodEmp  NUMBER(10) ,
   NivHab  NUMBER(2) ,
   PRIMARY KEY ( CodEmp , CodHab )
);

CREATE TABLE  hijo  (
   CodEmp  NUMBER(10)   ,
   NumHij  NUMBER(1)   ,
   FecNaHi  DATE,
   NomHi  VARCHAR2(40 CHAR)   ,
   PRIMARY KEY  ( CodEmp , NumHij )
 );

-- 3. INSERCIÓN DE DATOS

-- HABILIDAD 
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('FONTA','Fontanería');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('GEREN','Gerencia');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('GESCO','Gestión Contable');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('MARKE','Marketing');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('MECAN','Mecanografía');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('RELPU','Relaciones Públicas');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('TELEF','Telefonista');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('INFOR','Informática General');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('LIDER','Liderazgo de Equipos');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('VENTA','Técnicas de Venta');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('NEGOC','Negociación');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('IDIOE','Idiomas - Inglés');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('IDIOF','Idiomas - Francés');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('PROGR','Programación');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('CONTA','Contabilidad');
INSERT INTO  habilidad  ( CodHab , DesHab ) VALUES ('APROV','Aprovisionamiento');


-- CENTRO 
INSERT INTO  centro  ( CodCen , CodEmpDir , NomCen , DirCen , PobCen ) VALUES ('DIGE',1,'Dirección General','Av. Constitución 88','Murcia');
INSERT INTO  centro  ( CodCen , CodEmpDir , NomCen , DirCen , PobCen ) VALUES ('FAZS',6,'Fábrica Zona Sur','Pol. Ind. Gral. Bastarreche','Cartagena');
INSERT INTO  centro  ( CodCen , CodEmpDir , NomCen , DirCen , PobCen ) VALUES ('OFZS',5,'Oficinas Zona Sur','Pl. España 14','Cartagena');
INSERT INTO  centro  ( CodCen , CodEmpDir , NomCen , DirCen , PobCen ) VALUES ('OFZL',15,'Oficinas Zona Levante','Pl. Luceros 1','Alicante');

-- DEPARTAMENTO 
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('ADMZS',5,NULL,'OFZS','Administración Zona Sur',14000000,'P');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('DIRGE',1,NULL,'DIGE','Dirección General',26000000,'P');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('IN' || '&' || 'DI',2,'DIRGE','DIGE','Investigación y Diseño',25000000,'P');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('JEFZS',6,NULL,'FAZS','Jefatura Fábrica Zona Sur',6200000,'F');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('PROZS',9,'JEFZS','FAZS','Producción Zona Sur',108000000,'P');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('VENZS',3,'ADMZS','OFZS','Ventas Zona Sur',13500000,'F');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('MARKG',12,'DIRGE','DIGE','Marketing General',10000000,'P');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('VENZL',15,'DIRGE','OFZL','Ventas Zona Levante',8000000,'F');
INSERT INTO  departamento  ( CodDep , CodEmpDir , CodDepDep , CodCen , NomDep , PreAnu , TiDir ) VALUES ('RECHH',18,'DIRGE','DIGE','Recursos Humanos',7500000,'P');



ALTER TABLE empleado MODIFY (CodEmp NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 31) );
ALTER TABLE empleado MODIFY (CodEmp NUMBER(10) );


INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (1,'DIRGE','1111',TO_DATE('1972-07-01', 'YYYY-MM-DD'),TO_DATE('1961-08-07', 'YYYY-MM-DD'),'21451451V','Saladino Mandamás, Augusto',1,7200, NULL);
-- !! SOLUCIÓN COMPATIBLE: Se corrige el &
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (2,'IN' || '&' || 'DI','2233',TO_DATE('1991-06-14', 'YYYY-MM-DD'),TO_DATE('1970-06-08', 'YYYY-MM-DD'),'21231347K','Manrique Bacterio, Luisa',0,4500, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (3,'VENZS','2133',TO_DATE('1984-06-08', 'YYYY-MM-DD'),TO_DATE('1965-12-07', 'YYYY-MM-DD'),'23823930D','Monforte Cid, Roldán',1,5200, 600);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (4,'VENZS','3838',TO_DATE('1990-08-09', 'YYYY-MM-DD'),TO_DATE('1975-02-21', 'YYYY-MM-DD'),'38293923L','Topaz Illán, Carlos',0,3200, 450);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (5,'ADMZS','1239',TO_DATE('1976-08-07', 'YYYY-MM-DD'),TO_DATE('1958-03-08', 'YYYY-MM-DD'),'38223923T','Alada Veraz, Juana',1,6200, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (6,'JEFZS','23838',TO_DATE('1991-08-01', 'YYYY-MM-DD'),TO_DATE('1969-06-03', 'YYYY-MM-DD'),'26454122D','Gozque Altanero, Cándido',1,5000, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (7,'PROZS',NULL,TO_DATE('1994-06-30', 'YYYY-MM-DD'),TO_DATE('1975-08-07', 'YYYY-MM-DD'),'47123132D','Forzado López, Galeote',0,1600, 150);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (8,'PROZS',NULL,TO_DATE('1994-08-15', 'YYYY-MM-DD'),TO_DATE('1976-06-15', 'YYYY-MM-DD'),'32132154H','Mascullas Alto, Eloísa',1,1600, 150);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (9,'PROZS','12124',TO_DATE('1982-06-10', 'YYYY-MM-DD'),TO_DATE('1968-07-19', 'YYYY-MM-DD'),'11312121D','Mando Correa, Rosa',2,3100, 500);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (10,'PROZS',NULL,TO_DATE('1993-11-02', 'YYYY-MM-DD'),TO_DATE('1975-01-07', 'YYYY-MM-DD'),'32939393D','Mosc Amuerta, Mario',0,1300, 100);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (11,'MARKG','4401',TO_DATE('2005-01-10', 'YYYY-MM-DD'),TO_DATE('1980-05-15', 'YYYY-MM-DD'),'44001122A','Pérez Public, Ana',0,3000, 200);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (12,'MARKG','4400',TO_DATE('2004-11-01', 'YYYY-MM-DD'),TO_DATE('1978-11-20', 'YYYY-MM-DD'),'55112233B','Martínez Slogan, Luis',1,5500, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (13,'MARKG','4402',TO_DATE('2006-03-15', 'YYYY-MM-DD'),TO_DATE('1982-02-05', 'YYYY-MM-DD'),'66223344C','Gómez Redes, Sara',2,3100, 250);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (14,'VENZL','5501',TO_DATE('2008-02-01', 'YYYY-MM-DD'),TO_DATE('1985-07-30', 'YYYY-MM-DD'),'77334455D','Ruiz Trato, Javier',1,3500, 500);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (15,'VENZL','5500',TO_DATE('2007-10-01', 'YYYY-MM-DD'),TO_DATE('1975-04-12', 'YYYY-MM-DD'),'88445566E','López Cierre, María',2,6000, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (16,'VENZL','5502',TO_DATE('2009-05-20', 'YYYY-MM-DD'),TO_DATE('1988-01-10', 'YYYY-MM-DD'),'99556677F','Sánchez Puerta, David',0,3600, 550);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (17,'VENZS','3839',TO_DATE('2010-01-15', 'YYYY-MM-DD'),TO_DATE('1990-03-14', 'YYYY-MM-DD'),'11667788G','García Comisión, Elena',0,3300, 480);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (18,'RECHH','1120',TO_DATE('2003-06-01', 'YYYY-MM-DD'),TO_DATE('1972-09-09', 'YYYY-MM-DD'),'22778899H','Hernández Nómina, Pedro',1,5800, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (19,'RECHH','1121',TO_DATE('2004-09-10', 'YYYY-MM-DD'),TO_DATE('1980-12-01', 'YYYY-MM-DD'),'33889900J','Díaz Contrato, Laura',0,3400, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (20,'RECHH','1122',TO_DATE('2005-11-30', 'YYYY-MM-DD'),TO_DATE('1983-10-25', 'YYYY-MM-DD'),'44990011K','Moreno Selección, Carlos',3,3500, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (21,'PROZS',NULL,TO_DATE('1995-03-05', 'YYYY-MM-DD'),TO_DATE('1977-05-18', 'YYYY-MM-DD'),'55001122L','Romero Turno, Antonio',1,1700, 150);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (22,'PROZS',NULL,TO_DATE('1996-10-10', 'YYYY-MM-DD'),TO_DATE('1978-08-30', 'YYYY-MM-DD'),'66112233M','Navarro Calidad, Isabel',2,1650, 150);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (23,'PROZS','12125',TO_DATE('1997-07-20', 'YYYY-MM-DD'),TO_DATE('1979-04-02', 'YYYY-MM-DD'),'77223344N','Gil Cadena, Francisco',0,1750, 160);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (24,'IN' || '&' || 'DI','2234',TO_DATE('1993-09-01', 'YYYY-MM-DD'),TO_DATE('1972-11-11', 'YYYY-MM-DD'),'88334455P','Ortega Código, Miguel',1,4600, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (25,'IN' || '&' || 'DI','2235',TO_DATE('1994-01-15', 'YYYY-MM-DD'),TO_DATE('1973-01-20', 'YYYY-MM-DD'),'99445566Q','Reyes Dato, Clara',0,4700, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (26,'ADMZS','1240',TO_DATE('1980-05-01', 'YYYY-MM-DD'),TO_DATE('1962-07-07', 'YYYY-MM-DD'),'12345678A','Blanco Cuentas, José',2,2800, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (27,'ADMZS',NULL,TO_DATE('1982-10-10', 'YYYY-MM-DD'),TO_DATE('1964-02-14', 'YYYY-MM-DD'),'23456789B','Cano Archivo, Dolores',0,2750, NULL);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (28,'VENZS','3840',TO_DATE('2011-03-12', 'YYYY-MM-DD'),TO_DATE('1991-09-05', 'YYYY-MM-DD'),'34567890C','Soto Cliente, Mónica',1,3250, 460);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (29,'PROZS','12126',TO_DATE('1998-11-01', 'YYYY-MM-DD'),TO_DATE('1980-06-22', 'YYYY-MM-DD'),'45678901D','Pascual Taller, Rubén',1,1800, 170);
INSERT INTO  empleado  ( CodEmp , CodDep , ExTelEmp , FecInEmp , FecNaEmp , NifEmp , NomEmp , NumHi , SalEmp , ComEmp ) VALUES (30,'DIRGE','1112',TO_DATE('1995-02-01', 'YYYY-MM-DD'),TO_DATE('1970-10-10', 'YYYY-MM-DD'),'56789012E','Prieto Estratega, Vanesa',0,6500, NULL);


ALTER TABLE empleado MODIFY (CodEmp NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 31) );



-- HIJO 
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (1,1,TO_DATE('1989-06-07', 'YYYY-MM-DD'),'Saladino Oropel, Flavia');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (3,1,TO_DATE('1990-09-12', 'YYYY-MM-DD'),'Monforte Lemos, Jesús');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (5,1,TO_DATE('1982-03-06', 'YYYY-MM-DD'),'Pastora Alada, Mateo');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (8,1,TO_DATE('1994-03-14', 'YYYY-MM-DD'),'Fuerte Mascullas, Anacleto');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (9,1,TO_DATE('1988-02-28', 'YYYY-MM-DD'),'León Mando, Elvira');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (9,2,TO_DATE('1990-07-18', 'YYYY-MM-DD'),'León Mando, Plácido');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (12,1,TO_DATE('2005-08-10', 'YYYY-MM-DD'),'Martínez Sol, Lucía');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (13,1,TO_DATE('2007-01-20', 'YYYY-MM-DD'),'Gómez Clic, Hugo');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (13,2,TO_DATE('2009-04-15', 'YYYY-MM-DD'),'Gómez Clic, Pablo');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (14,1,TO_DATE('2010-11-05', 'YYYY-MM-DD'),'Ruiz Bueno, Sofía');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (15,1,TO_DATE('2008-03-18', 'YYYY-MM-DD'),'López Venta, Daniel');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (15,2,TO_DATE('2011-09-22', 'YYYY-MM-DD'),'López Venta, Alba');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (18,1,TO_DATE('2004-12-30', 'YYYY-MM-DD'),'Hernández Salario, Marcos');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (20,1,TO_DATE('2006-02-14', 'YYYY-MM-DD'),'Moreno Talento, Emma');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (20,2,TO_DATE('2008-07-07', 'YYYY-MM-DD'),'Moreno Talento, Martín');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (20,3,TO_DATE('2010-05-19', 'YYYY-MM-DD'),'Moreno Talento, Julia');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (21,1,TO_DATE('1998-01-01', 'YYYY-MM-DD'),'Romero Pieza, Iván');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (22,1,TO_DATE('1999-06-10', 'YYYY-MM-DD'),'Navarro Test, Carla');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (22,2,TO_DATE('2001-11-25', 'YYYY-MM-DD'),'Navarro Test, Bruno');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (24,1,TO_DATE('1996-04-04', 'YYYY-MM-DD'),'Ortega Byte, Ana');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (26,1,TO_DATE('1985-09-12', 'YYYY-MM-DD'),'Blanco Debe, Sergio');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (26,2,TO_DATE('1988-03-20', 'YYYY-MM-DD'),'Blanco Haber, María');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (28,1,TO_DATE('2013-08-08', 'YYYY-MM-DD'),'Soto Bueno, Leo');
INSERT INTO  hijo  ( CodEmp , NumHij , FecNaHi , NomHi ) VALUES (29,1,TO_DATE('2000-10-28', 'YYYY-MM-DD'),'Pascual Llave, Manuel');

-- HABEMP (Habilidades de Empleados)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GEREN',1,10);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('RELPU',1,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MARKE',3,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GESCO',5,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('RELPU',5,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('FONTA',8,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('INFOR',2,9); -- Manrique Bacterio (IN&DI)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('PROGR',2,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',3,9); -- Monforte Cid (VENZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('NEGOC',3,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',4,8); -- Topaz Illán (VENZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('NEGOC',4,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOE',4,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('FONTA',7,8); -- Forzado López (PROZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MECAN',7,6);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MARKE',11,7); -- Pérez Public (MARKG)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOE',11,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MARKE',12,10); -- Martínez Slogan (MARKG Dir)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GEREN',12,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('LIDER',12,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('RELPU',12,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MARKE',13,8); -- Gómez Redes (MARKG)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GESCO',13,6);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',14,9); -- Ruiz Trato (VENZL)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('NEGOC',14,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',15,10); -- López Cierre (VENZL Dir)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GEREN',15,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('LIDER',15,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOF',15,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',16,7); -- Sánchez Puerta (VENZL)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOE',16,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',17,7); -- García Comisión (VENZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('TELEF',17,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GEREN',18,8); -- Hernández Nómina (RECHH Dir)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('LIDER',18,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('NEGOC',18,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('RELPU',18,10);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('RELPU',19,8); -- Díaz Contrato (RECHH)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MECAN',19,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GESCO',20,8); -- Moreno Selección (RECHH)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOE',20,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('INFOR',24,10); -- Ortega Código (IN&DI)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('PROGR',24,10);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('INFOR',25,8); -- Reyes Dato (IN&DI)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('PROGR',25,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GESCO',26,10); -- Blanco Cuentas (ADMZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MECAN',26,9);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('TELEF',26,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GESCO',27,8); -- Cano Archivo (ADMZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('MECAN',27,8);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('VENTA',28,7); -- Soto Cliente (VENZS)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOE',28,6);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('GEREN',30,9); -- Prieto Estratega (DIRGE)
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('LIDER',30,10);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOE',30,10);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('IDIOF',30,7);
INSERT INTO  habemp  ( CodHab , CodEmp , NivHab ) VALUES ('NEGOC',30,9);


-- 4. CREACIÓN DE CONSTRAINTS (FOREIGN KEYS)
-- Se añaden al final para permitir la carga de datos
-- en el orden deseado sin fallos de integridad referencial.

ALTER TABLE departamento
ADD CONSTRAINT fk_dep_cen FOREIGN KEY (CodCen) REFERENCES centro(CodCen);

ALTER TABLE departamento
ADD CONSTRAINT fk_dep_emp FOREIGN KEY (CodEmpDir) REFERENCES empleado(CodEmp);

ALTER TABLE departamento
ADD CONSTRAINT fk_dep_dep FOREIGN KEY (CodDepDep) REFERENCES departamento(CodDep);

ALTER TABLE empleado
ADD CONSTRAINT fk_emp_dep FOREIGN KEY (CodDep) REFERENCES departamento(CodDep);

-- La FK de centro a empleado (CodEmpDir) debe añadirse
-- después de que los empleados estén insertados.
ALTER TABLE centro
ADD CONSTRAINT fk_cen_emp FOREIGN KEY (CodEmpDir) REFERENCES empleado(CodEmp);

ALTER TABLE hijo
ADD CONSTRAINT fk_hij_emp FOREIGN KEY (CodEmp) REFERENCES empleado(CodEmp);

ALTER TABLE habemp
ADD CONSTRAINT fk_habemp_emp FOREIGN KEY (CodEmp) REFERENCES empleado(CodEmp);

ALTER TABLE habemp
ADD CONSTRAINT fk_habemp_hab FOREIGN KEY (CodHab) REFERENCES habilidad(CodHab);

COMMIT;

-- 5. FINALIZACIÓN
-- Script finalizado.
