CREATE TABLE EMPLEADOS (
DNI NUMBER(8),
NOMBRE VARCHAR2(10 CHAR),
APELLIDO1 VARCHAR2(15 CHAR),
APELLIDO2 VARCHAR2(15 CHAR),
DIRECCI1 VARCHAR2(25 CHAR),
DIRECCI2 VARCHAR2(20 CHAR),
CIUDAD VARCHAR2(20 CHAR),
PROVINCIA VARCHAR2(20 CHAR),
COD_POSTAL VARCHAR2(5 CHAR),
SEXO VARCHAR2(1 CHAR),
FECHA_NAC DATE
);
CREATE TABLE DEPARTAMENTOS (
DPTO_COD NUMBER(5),
NOMBRE_DPTO VARCHAR2(30 CHAR),
DPTO_PADRE NUMBER(5),
PRESUPUESTO NUMBER,
PRES_ACTUAL NUMBER
);
CREATE TABLE ESTUDIOS (
EMPLEADO_DNI NUMBER(8),
UNIVERSIDAD NUMBER(5),
ANYO NUMBER,
GRADO VARCHAR2(3 CHAR),
ESPECIALIDAD VARCHAR2(20 CHAR)
);
CREATE TABLE UNIVERSIDADES (
UNIV_COD NUMBER(5),
NOMBRE_UNIV VARCHAR2(25 CHAR),
CIUDAD VARCHAR2(20 CHAR),
MUNICIPIO VARCHAR2(2 CHAR),
COD_POSTAL VARCHAR2(5 CHAR)
);
CREATE TABLE HISTORIAL_LABORAL(
EMPLEADO_DNI NUMBER(8),
TRABAJO_COD NUMBER(5),
FECHA_INICIO DATE,
FECHA_FIN DATE,
DPTO_DOC NUMBER(5),
SUPERVISOR_DNI NUMBER(8)
);
CREATE TABLE HISTORIAL_SALARIAL(
EMPLEADO_DNI NUMBER(8),
SALARIO NUMBER,
FECHA_COMIENZO DATE,
FECHA_FIN DATE
);
CREATE TABLE TRABAJOS (
TRABAJO_COD NUMBER(5),
NOMBRE_TRAB VARCHAR2(20),
SALARIO_MIN NUMBER(2),
SALARIO_MAX NUMBER(2)
);

------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------

ALTER TABLE EMPLEADOS MODIFY nombre NOT NULL;
ALTER TABLE EMPLEADOS MODIFY apellido1 NOT NULL;

ALTER TABLE DEPARTAMENTOS MODIFY nombre_dpto NOT NULL;
ALTER TABLE DEPARTAMENTOS MODIFY presupuesto NOT NULL;

ALTER TABLE HISTORIAL_SALARIAL MODIFY salario NOT NULL;

ALTER TABLE TRABAJOS MODIFY salario_min NOT NULL;
ALTER TABLE TRABAJOS MODIFY salario_max NOT NULL;

ALTER TABLE EMPLEADOS ADD CONSTRAINT chk_sexo CHECK (sexo IN ('M','F','N'));

ALTER TABLE DEPARTAMENTOS  ADD CONSTRAINT unique_departamentos UNIQUE (nombre_dpto);
ALTER TABLE TRABAJOS MODIFY nombre_trab UNIQUE;

CREATE USER ejerciciosddl IDENTIFIED BY 123 quota unlimited
ON users;
GRANT CONNECT, resource TO ejerciciosddl;








