CREATE TABLE recintos(
cod_recinto NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre varchar2(10) NOT NULL,
direccion varchar2(50) NOT NULL,
ciudad varchar2(10) NOT NULL,
telefono NUMBER (10) NOT NULL,
horario varchar2(20)NOT NULL,
CONSTRAINT pk_cod_recinto_recintos PRIMARY KEY (cod_recinto)

);

CREATE TABLE espectaculo(
cod_espectaculo NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(20) NOT NULL,
tipo VARCHAR2(10) NOT NULL,
fecha_inicial DATE NOT NULL,
fecha_final DATE NOT NULL,
interprete VARCHAR2(20) NOT NULL,
cod_recinto NUMBER,
CONSTRAINT pk_cod_esp_tb_esp PRIMARY KEY (cod_espectaculo,cod_recinto),
CONSTRAINT fk_cod_rec_tb_esp FOREIGN KEY (cod_recinto) REFERENCES recintos (cod_recinto)
);

CREATE TABLE representaciones (
cod_espectaculo NUMBER,
cod_recinto NUMBER,
fecha DATE,
hora TIMESTAMP,
CONSTRAINT pk_cod_esp_tb_rep PRIMARY KEY (cod_espectaculo,cod_recinto,fecha,hora),
CONSTRAINT fk_cod_esp_tb_rep FOREIGN KEY (cod_espectaculo,cod_recinto) REFERENCES ESPECTACULO (cod_espectaculo,cod_recinto)
);

CREATE TABLE precios_espectaculos (
cod_espectaculo NUMBER,
cod_recinto NUMBER,
zona VARCHAR2(10),
precio NUMBER(6,2) CHECK (precio > 0) NOT NULL,
CONSTRAINT fk_pre_esp_tb_pre FOREIGN KEY (cod_espectaculo,cod_recinto) REFERENCES espectaculo (cod_espectaculo,cod_recinto),
CONSTRAINT pk_pre_esp_tb_pre PRIMARY KEY (cod_espectaculo,cod_recinto,zona)

);

CREATE TABLE zonas_recintos (
cod_recinto NUMBER,
zona VARCHAR2(10),
capacidad NUMBER(3) CHECK (capacidad > 0) NOT NULL,
CONSTRAINT pk_zon_rec PRIMARY KEY (cod_recinto,zona),
CONSTRAINT fk_cod_rec_tb_zon_rec FOREIGN KEY (cod_recinto) REFERENCES recintos (cod_recinto)
);

CREATE TABLE asientos (
cod_recinto NUMBER,
zona varchar2(10),
fila varchar2(3),
numero number(3),
CONSTRAINT pk_asi PRIMARY KEY (cod_recinto,zona,fila,numero),
CONSTRAINT fk_asi FOREIGN KEY (cod_recinto,zona) REFERENCES zonas_recintos (cod_recinto,zona)
);

CREATE TABLE espectadores (
dni_cliente varchar2(9) PRIMARY KEY,
nombre varchar2(20) NOT NULL,
direccion varchar2(50) NOT NULL,
telefono number(10) NOT NULL,
ciudad varchar2(20) NOT NULL,
ntarjeta number(10) NOT NULL
);

CREATE TABLE entradas (
cod_espectaculo NUMBER,
cod_recinto NUMBER,
fecha DATE,
hora TIMESTAMP,
fila varchar2(3),
numero NUMBER,
zona varchar2(10),
dni_cliente varchar2(9),
CONSTRAINT pk_entr PRIMARY KEY (cod_espectaculo,cod_recinto,fecha,hora,fila,numero,zona),
CONSTRAINT fk_ent_rep FOREIGN KEY (cod_espectaculo,cod_recinto,fecha,hora) 
REFERENCES representaciones (cod_espectaculo,cod_recinto,fecha,hora),
CONSTRAINT fk_ent_asi FOREIGN KEY (cod_recinto,zona,fila,numero) REFERENCES asientos (cod_recinto,zona,fila,numero),
CONSTRAINT fk_ent_esp FOREIGN KEY (dni_cliente) REFERENCES espectadores (dni_cliente)
);



--CREATE USER EMPRESA IDENTIFIED BY oracle123 QUOTA UNLIMITED ON USERS;
--GRANT RESOURCE, CONNECT TO EMPRESA;


























