SELECT ip.FECHA_INCIDENTE, ip.LUGAR, tipo, ip.DESCRIPCION 
FROM INFORMES_POLICIALES ip 
WHERE ip.LUGAR IN ('InnovaTech') ORDER BY FECHA_INCIDENTE desc;

SELECT nombre, e.CALLE, e.NUMERO   
FROM EMPLEADOS e WHERE e.CALLE IN ('Calle Pez'); 

SELECT d.NOMBRE , d.EDIFICIO , d.ID_DEP  FROM DEPARTAMENTOS d ;

SELECT  lp.ID_PUERTA , lp.EVENTO, lp.FECHA_HORA   FROM LOG_PUERTAS lp 
WHERE lp.ID_PUERTA IN ('SALA_CPD_01');

SELECT ta.ID_EMP, e.NOMBRE, e.APELLIDO
FROM LOG_PUERTAS lp
JOIN TARJETAS_ACCESO ta ON lp.NUM_TARJETA = ta.NUM_TARJETA
JOIN EMPLEADOS e ON ta.ID_EMP = e.ID_EMP
WHERE lp.ID_PUERTA = 'SALA_CPD_01'
  AND lp.EVENTO = 'ENTRADA';

SELECT c.id_REMITENTE, e.NOMBRE, e.APELLIDO, c.FECHA_ENVIO
FROM CORREOS c
JOIN EMPLEADOS e ON c.ID_REMITENTE = e.ID_EMP
WHERE c.DESTINATARIO = 'admin@innovatech.com';

SELECT e.NOMBRE, e.APELLIDO, d.TEXTO
FROM DECLARACIONES d
JOIN EMPLEADOS e ON d.ID_EMP = e.ID_EMP
WHERE d.ID_EMP IN (
  SELECT ta.ID_EMP
  FROM LOG_PUERTAS lp
  JOIN TARJETAS_ACCESO ta ON lp.NUM_TARJETA = ta.NUM_TARJETA
  WHERE lp.ID_PUERTA = 'SALA_CPD_01'
    AND lp.EVENTO = 'ENTRADA'
)
AND d.TEXTO LIKE '%correo%'
AND d.TEXTO LIKE '%terminal%';

SELECT distinct d.TEXTO,   FROM DECLARACIONES d ;
SELECT distinct c.DESTINATARIO  FROM CORREOS c ;