CREATE TABLE curso (
cod_curso NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(10) NOT NULL UNIQUE,
modalidad VARCHAR2(10) CHECK (modalidad IN ('online','presencial','mixta')),
precio_base NUMBER (6,2) CHECK (precio_base > 0) NOT NULL,
nivel VARCHAR2(10) NOT NULL,
horas NUMBER (3) CHECK (horas>0) NOT NULL,
CONSTRAINT pk_curso PRIMARY KEY (cod_curso)
);

CREATE TABLE edicion (
cod_edicion NUMBER GENERATED BY DEFAULT AS IDENTITY,
cod_curso NUMBER,
fecha_inicio DATE NOT NULL,
fecha_fin DATE NOT NULL,
aforo NUMBER (3) CHECK (aforo>0) NOT NULL,
aula VARCHAR2(10) NOT NULL,
estado VARCHAR2(20) CHECK (estado IN ('planificada','abierta','cerrada','cancelada')),
CONSTRAINT pk_edicion PRIMARY KEY (cod_edicion),
CONSTRAINT fk_cod_curso_tb_edi FOREIGN KEY (cod_curso) REFERENCES curso (cod_curso),
CONSTRAINT ck_fechas CHECK (fecha_inicio <= fecha_fin)
);

CREATE TABLE profesor (
cod_prof NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(20) NOT NULL,
apellidos VARCHAR2(30) NOT NULL,
email VARCHAR2(50) NOT NULL UNIQUE,
telefono NUMBER(10) NOT NULL,
CONSTRAINT pk_cod_prof_prof PRIMARY KEY (cod_prof)
);

CREATE TABLE alumno (
cod_alumno NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(20) NOT NULL,
apellidos VARCHAR2(20) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
telefono NUMBER (10) NOT NULL, 
domicilio1 VARCHAR2(50) NOT NULL,
domicilio2 VARCHAR2(50),
CONSTRAINT pk_cod_alumno_tb_alumno PRIMARY KEY (cod_alumno)
);

CREATE TABLE matricula (
cod_matricula NUMBER GENERATED BY DEFAULT AS IDENTITY,
cod_alumno NUMBER,
cod_edicion NUMBER,
fecha_matricula DATE NOT NULL,
estado VARCHAR2(10) CHECK(estado IN ('activa','anulada','finalizada')),
CONSTRAINT pk_cod_mat_tb_mat PRIMARY KEY (cod_matricula),
CONSTRAINT fk_cod_alu_tb_alu FOREIGN KEY (cod_alumno) 
REFERENCES ALUMNO (cod_alumno),
CONSTRAINT fk_cod_edi_tb_alu FOREIGN KEY (cod_edicion) 
REFERENCES EDICION  (cod_edicion)
);

CREATE TABLE pago (
cod_pago NUMBER GENERATED BY DEFAULT AS IDENTITY,
cod_matricula NUMBER,
fecha_pago DATE NOT NULL,
metodo VARCHAR2(10) CHECK (metodo IN ('tarjeta','transfetencia','efectivo')),
importe NUMBER (6,2) CHECK (importe > 0) NOT NULL,
CONSTRAINT pk_cod_pago_pago PRIMARY KEY (cod_pago),
CONSTRAINT fk_cod_mat_tb_pag FOREIGN KEY (cod_matricula) 
REFERENCES MATRICULA (cod_matricula)
);

CREATE TABLE curso_profesor (
cod_curso NUMBER,
cod_prof NUMBER,
CONSTRAINT pk_cur_pro PRIMARY KEY (cod_curso,cod_prof),
CONSTRAINT fk_cod_cur_tb_cur FOREIGN KEY (cod_curso) REFERENCES CURSO (cod_curso),

CONSTRAINT fk_cod_pro_tb_cur FOREIGN KEY (cod_prof) REFERENCES PROFESOR  (cod_prof)

);

