CREATE TABLE localidad (
cod_localidad NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(20) NOT NULL,
CONSTRAINT pk_cod_localidad PRIMARY KEY (cod_localidad)
);

CREATE TABLE pub (
cod_pub NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre VARCHAR2(20) NOT NULL,
licencia_fiscal VARCHAR2(20) NOT NULL,
domicilio VARCHAR2(50),
fecha_apertura DATE NOT NULL,
horario VARCHAR2(5) CHECK (horario IN ('HOR1', 'HOR2', 'HOR3')),
cod_localidad NUMBER,
CONSTRAINT fk_cod_localidad FOREIGN KEY (cod_localidad) REFERENCES localidad (cod_localidad),
CONSTRAINT pk_cod_pub PRIMARY KEY (cod_pub)
);

CREATE TABLE titular (
dni_titular VARCHAR2(9) NOT NULL PRIMARY KEY ,
nombre VARCHAR2(20) NOT NULL,
domicilio VARCHAR2(50),
cod_pub NUMBER,
CONSTRAINT fk_cod_pub FOREIGN KEY (cod_pub) REFERENCES pub (cod_pub)
);

CREATE TABLE empleado (
dni_empleado VARCHAR2(9) NOT NULL PRIMARY KEY,
nombre VARCHAR2(20) NOT NULL,
domicilio VARCHAR2(50)
);

CREATE TABLE existencias (
cod_articulo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre VARCHAR2(20) NOT NULL,
cantidad NUMBER(3) CHECK (cantidad > 0) NOT NULL, ---  <
precio NUMBER (5,2) NOT NULL,
cod_pub NUMBER,
CONSTRAINT fk_cod_pub_existencias FOREIGN KEY (cod_pub) REFERENCES pub (cod_pub)
);

CREATE TABLE pub_empleado (
cod_pub NUMBER,
dni_empleado VARCHAR2(9),
funcion VARCHAR2(10) CHECK (funcion IN ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA')),
CONSTRAINT pk_pub_empleado PRIMARY KEY (cod_pub, dni_empleado, funcion),
CONSTRAINT fk_cod_pub_pub_empleado FOREIGN KEY (cod_pub) REFERENCES pub (cod_pub),
CONSTRAINT fk_dni_empleado_pub_empleado FOREIGN KEY (dni_empleado) REFERENCES empleado (dni_empleado)
);


--DROP TABLE LOCALIDAD;
--DROP TABLE empleado;
--DROP TABLE pub;
--DROP TABLE titular;
--DROP TABLE EXISTENCIAS ;