
-- tabla clientes
CREATE TABLE clientes (
id_cliente NUMBER GENERATED	BY	DEFAULT	AS	IDENTITY,
nombre VARCHAR2(50 CHAR) NOT NULL,
apellidos VARCHAR(100 CHAR) NOT NULL,
email VARCHAR2(100 CHAR) NOT NULL,
fecha_registro DATE DEFAULT SYSDATE,
CONSTRAINT pk_cli_id PRIMARY KEY (id_cliente),
CONSTRAINT un_cli_ema UNIQUE (email)
);

-- tabla categorias

CREATE TABLE categorias (
id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre_categoria VARCHAR2 (100 CHAR) NOT NULL,
CONSTRAINT pk_cat_id PRIMARY KEY (id_categoria),
CONSTRAINT un_cat_nom UNIQUE (nombre_categoria)
);

-- tabla productos

CREATE TABLE  productos (
id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY,
nombre_producto VARCHAR2(150 CHAR) NOT NULL,
descripcion CLOB,
precio NUMBER(10,2) NOT NULL,
stock NUMBER(6) NOT NULL,
id_categoria NUMBER,
CONSTRAINT pk_pro_idp PRIMARY KEY (id_producto),
CONSTRAINT fk_pro_idc FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS (id_categoria),
CONSTRAINT chk_pro_pre CHECK (precio > 0),
CONSTRAINT chk_pro_sto CHECK (stock >= 0)
);


-- tabla pedidos

CREATE TABLE pedidos (
id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY,
id_cliente NUMBER NOT NULL,
fecha_pedido DATE DEFAULT SYSDATE,
estado VARCHAR2(20 CHAR),
CONSTRAINT fk_ped_idc FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
CONSTRAINT chk_ped_est CHECK (estado IN ('Pendiente', 'Enviado', 'Entregado'))
);

ALTER TABLE PEDIDOS ADD CONSTRAINT pk_ped_id PRIMARY KEY (id_pedido);

-- tabla detalle pedidos

CREATE TABLE detalles_pedidos (
id_pedido NUMBER,
id_producto NUMBER,
cantidad NUMBER(5) NOT NULL,
precio_unitario NUMBER(10,2)  NOT NULL,
CONSTRAINT pk_det_idped_idprod PRIMARY KEY (id_pedido, id_producto),
CONSTRAINT fk_det_idped FOREIGN KEY (id_pedido) REFERENCES PEDIDOS (id_pedido),
CONSTRAINT fk_det_idpro FOREIGN KEY (id_producto) REFERENCES PRODUCTOS (id_producto),
CONSTRAINT chk_det_can CHECK (cantidad > 0)
);
 

-- indice sobre productos

CREATE INDEX idx_pro_nom ON PRODUCTOS(nombre_producto);


-- añadir telefonos a clientes

ALTER TABLE CLIENTES ADD(
telefono VARCHAR2(15) CONSTRAINT un_cli_tel UNIQUE
);

ALTER TABLE PRODUCTOS ADD (
CONSTRAINT chk_prec CHECK (precio_1go >= 0);
);

DROP TABLE pedidos;


SELECT object_name, object_type
FROM user_objects
WHERE object_name = 'PEDIDOS';

DROP TABLE pedidos CASCADE CONSTRAINTS;








