
-- 1
CREATE TABLE propietarios (
propietario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
dni VARCHAR2(9) UNIQUE NOT NULL,
nombre_completo VARCHAR2(80) NOT NULL,
direccion VARCHAR2(150),
telefono VARCHAR2(15) NOT NULL,
email VARCHAR2(60) UNIQUE
);


-- 2

CREATE TABLE veterinarios (
veterinario_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
num_colegiado VARCHAR2(20) UNIQUE NOT NULL,
nombre VARCHAR2(50) NOT NULL,
apellidos VARCHAR2(70) NOT NULL,
especialidad VARCHAR2(40), 
fecha_alta DATE DEFAULT SYSDATE,
salario NUMBER(9,2),
CONSTRAINT chk_especialidad_tipo CHECK (especialidad IN ('Medicina General', 'Cirugia', 
'Dermatologo', 'Oftalmologia', 'Traumatologia')),
CONSTRAINT chk_salario_rango CHECK (salario BETWEEN 2000 AND 8000)
);

ALTER TABLE VETERINARIOS ADD CONSTRAINT pk_vet_id PRIMARY KEY (veterinario_id);

-- 3

CREATE TABLE mascotas (
mascota_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
chip VARCHAR2(15) UNIQUE NOT NULL,
nombre VARCHAR2(40) NOT NULL,
especie VARCHAR2(30) CHECK (especie IN ('Perro', 'Gato', 'Ave', 'Roedor', 'Reptil')),
raza VARCHAR2(50),
fecha_nacimiento DATE,
peso NUMBER(5,2) CHECK (peso > 0),
propietario_id NUMBER,
CONSTRAINT fk_propietario_id FOREIGN KEY (propietario_id) REFERENCES PROPIETARIOS (propietario_id)
);



-- 4

CREATE TABLE citas (
cita_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
mascota_id NUMBER NOT NULL,
veterinario_id NUMBER NOT NULL,
fecha_hora TIMESTAMP NOT NULL,
motivo VARCHAR2(200) NOT NULL,
estado VARCHAR2(20) CHECK (estado IN ('Programada', 'Realizada', 'Cancelada', 'No Asistio')),
observaciones VARCHAR2(500),
CONSTRAINT fk_mascota_id FOREIGN KEY (mascota_id) REFERENCES MASCOTAS (mascota_id),
CONSTRAINT fk_veterinario_id FOREIGN KEY (veterinario_id) REFERENCES VETERINARIOS (veterinario_id)
);


-- 5 

CREATE TABLE tratamientos (
tratamiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
codigo VARCHAR2(10) UNIQUE NOT NULL,
nombre VARCHAR2(60)NOT NULL,
descripcion VARCHAR2(200),
coste NUMBER(8,2) CHECK (coste > 0)
);

CREATE TABLE historial_tratamientos (
mascota_id NUMBER NOT NULL,
tratamiento_id NUMBER NOT NULL,
fecha_aplicacion DATE NOT NULL,
veterinario_id NUMBER NOT NULL,
dosis VARCHAR2(50),
notas VARCHAR2(300),
-- primary key compuesta
CONSTRAINT pk_historial_tratamientos PRIMARY KEY (mascota_id, tratamiento_id, fecha_aplicacion),

-- foreign key
CONSTRAINT fk_mascota_id_historial_tratamientos FOREIGN KEY (mascota_id) REFERENCES MASCOTAS (mascota_id),
CONSTRAINT fk_tratamiento_id_historial_tratamientos FOREIGN KEY (tratamiento_id) REFERENCES TRATAMIENTOS (tratamiento_id),
CONSTRAINT fk_veterinario_id_historial_tratamientos FOREIGN KEY (veterinario_id) REFERENCES VETERINARIOS (veterinario_id)
);

-- modificaciones

ALTER TABLE VETERINARIOS 
ADD turno VARCHAR2(10) 
CONSTRAINT ck_vet_turno CHECK (turno IN ('Manana', 'Tarde', 'Noche'));

ALTER TABLE VETERINARIOS ADD 
activo 	CHAR(1) DEFAULT 'S' CONSTRAINT ck_vet_activo CHECK (activo IN ('S', 'N'));

ALTER TABLE VETERINARIOS MODIFY nombre VARCHAR2(100);

ALTER TABLE VETERINARIOS DROP CONSTRAINT chk_especialidad_tipo;

ALTER TABLE VETERINARIOS DROP CONSTRAINT chk_salario_rango;

ALTER TABLE VETERINARIOS ADD CONSTRAINT ck_sal_vet CHECK (salario BETWEEN 2500 AND 10000);

ALTER TABLE VETERINARIOS ADD fecha_nacimiento DATE NOT NULL;

ALTER TABLE VETERINARIOS DROP COLUMN fecha_alta;

-- tablas proveedores

CREATE TABLE proveedores (
proveedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cif VARCHAR2(12) UNIQUE NOT NULL,
nombre_empresa VARCHAR2(80) NOT NULL,
telefono VARCHAR2(15) NOT NULL,
email VARCHAR2(60) UNIQUE
);

CREATE TABLE productos_veterinarios (
producto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
codigo_barras NUMBER(13) UNIQUE NOT NULL,
nombre_producto VARCHAR2(100) NOT NULL,
tipo_producto VARCHAR(30) 
CONSTRAINT ck_tipo_producto CHECK (tipo_producto IN ('Medicamento', 'Alimento', 'Accesorio', 'Higiene')),
proveedor_id NUMBER NOT NULL,
precio_compra NUMBER(8,2) CHECK (PRECIO_COMPRA > 0),
precio_venta NUMBER(8,2) CHECK (PRECIO_VENTA > 0),
stock_actual NUMBER(5) DEFAULT 0 CHECK (stock_actual >= 0),
stock_minimo NUMBER(5) CHECK (STOCK_MINIMO >= 0),
CONSTRAINT fk_prov_id_prod_vet FOREIGN KEY (proveedor_id) REFERENCES PROVEEDORES (proveedor_id)
);

CREATE TABLE ventas (
venta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fecha_venta TIMESTAMP DEFAULT SYSTIMESTAMP,
propietario_id NUMBER,
total NUMBER(10,2) CHECK (total > 0),
CONSTRAINT fk_prop_id_ventas FOREIGN KEY (propietario_id) REFERENCES PROPIETARIOS (propietario_id)
);

CREATE TABLE detalles_venta (
venta_id NUMBER,
producto_id NUMBER,
cantidad NUMBER(5) CHECK (cantidad > 0),
precio_unitario NUMBER(8,2) CHECK (precio_unitario > 0),
subtotal NUMBER(10,2) CHECK (subtotal > 0),
CONSTRAINT pk_detalles_venta PRIMARY KEY (venta_id, producto_id),
CONSTRAINT fk_venta_id FOREIGN KEY (venta_id) REFERENCES VENTAS (venta_id),
CONSTRAINT fk_producto_vet FOREIGN KEY (producto_id) REFERENCES PRODUCTOS_VETERINARIOS (producto_id)
);

-- indice

CREATE INDEX idx_nombre_producto ON PRODUCTOS_VETERINARIOS(nombre_producto);

ALTER TABLE PRODUCTOS_VETERINARIOS ADD caducidad DATE; 

ALTER TABLE PROPIETARIOS ADD descuento_fidelidad NUMBER(2) DEFAULT 0 CHECK (descuento_fidelidad BETWEEN 0 AND 30)

ALTER TABLE PRODUCTOS_VETERINARIOS RENAME COLUMN stock_actual TO unidades_disponibles;

ALTER TABLE VENTAS ADD metodo_pago VARCHAR2(20) CHECK (metodo_pago IN ('Efectivo', 'Tarjeta', 'Transferencia'));



















